from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Sequence

try:
    from scripts.summarize_status import expand_paths, normalize_heading
    from scripts.validate_templates import table_blocks, table_cells
except ModuleNotFoundError:
    from summarize_status import expand_paths, normalize_heading
    from validate_templates import table_blocks, table_cells


GENERATED_MARKER = "<!-- generated by scripts/audit_handover_acceptance.py -->"
IDENTIFIER_PATTERN = re.compile(r"^[A-Z][A-Z0-9]*(?:-[A-Z0-9]+)*-\d+$")

PUNCH_COLUMNS = {
    "item_id": ("ID", "Punch ID", "Item ID"),
    "severity": ("Severity",),
    "finding": ("Finding or Nonconformance", "Finding"),
    "owner": ("Owner",),
    "evidence_link": ("Evidence Link",),
    "target_close_date": ("Target Close Date",),
    "status": ("Status",),
    "closeout_note": ("Verification / Closeout Note", "Closeout Note"),
}
RISK_COLUMNS = {
    "risk_id": ("ID", "Residual-Risk ID", "Risk ID"),
    "source_item_id": ("Source Item ID", "Source Punch ID"),
    "description": ("Risk Description",),
    "interim_control": ("Interim Control",),
    "owner": ("Owner",),
    "approval": ("Approval",),
    "target_close_date": ("Target Close Date",),
    "status": ("Status",),
    "closeout_evidence": ("Closeout Evidence",),
}
ACCEPTANCE_COLUMNS = {
    "acceptance_id": ("Acceptance ID",),
    "decision": ("Decision",),
    "residual_risk_ids": ("Residual-Risk IDs", "Residual Risk IDs"),
    "approved_by": ("Approved By",),
    "approval_date": ("Approval Date",),
    "evidence_location": ("Evidence Location",),
}


@dataclass(frozen=True)
class HandoverPolicy:
    missing_values: tuple[str, ...]
    severities: tuple[str, ...]
    punch_statuses: tuple[str, ...]
    open_punch_statuses: tuple[str, ...]
    deferred_punch_statuses: tuple[str, ...]
    closed_punch_statuses: tuple[str, ...]
    accepted_risk_statuses: tuple[str, ...]
    closed_risk_statuses: tuple[str, ...]
    release_decisions: tuple[str, ...]
    conditional_decisions: tuple[str, ...]
    pending_decisions: tuple[str, ...]
    blocking_severities: tuple[str, ...]
    non_deferrable_severities: tuple[str, ...]


@dataclass(frozen=True)
class PunchItem:
    source: str
    line: int
    item_id: str
    severity: str
    finding: str
    owner: str
    evidence_link: str
    target_close_date: str
    status: str
    closeout_note: str


@dataclass(frozen=True)
class ResidualRisk:
    source: str
    line: int
    risk_id: str
    source_item_id: str
    description: str
    interim_control: str
    owner: str
    approval: str
    target_close_date: str
    status: str
    closeout_evidence: str


@dataclass(frozen=True)
class AcceptanceDecision:
    source: str
    line: int
    acceptance_id: str
    decision: str
    residual_risk_ids: tuple[str, ...]
    approved_by: str
    approval_date: str
    evidence_location: str


@dataclass(frozen=True)
class HandoverIssue:
    source: str
    line: int
    record_id: str
    kind: str
    detail: str


def _string_tuple(value: object, context: str) -> tuple[str, ...]:
    if not isinstance(value, list) or not value:
        raise ValueError(f"{context} must be a nonempty list")
    if any(not isinstance(item, str) or not item.strip() for item in value):
        raise ValueError(f"{context} must contain nonempty strings")
    values = tuple(item.strip() for item in value)
    normalized = [normalize_heading(item) for item in values]
    if len(normalized) != len(set(normalized)):
        raise ValueError(f"{context} contains case-insensitive duplicates")
    return values


def load_handover_policy(path: Path) -> HandoverPolicy:
    """Load and strictly validate the cross-register acceptance policy."""

    document = json.loads(path.read_text(encoding="utf-8"))
    fields = {
        "missing_values",
        "severities",
        "punch_statuses",
        "open_punch_statuses",
        "deferred_punch_statuses",
        "closed_punch_statuses",
        "accepted_risk_statuses",
        "closed_risk_statuses",
        "release_decisions",
        "conditional_decisions",
        "pending_decisions",
        "blocking_severities",
        "non_deferrable_severities",
    }
    if not isinstance(document, dict):
        raise ValueError("handover policy root must be a JSON object")
    unknown = sorted(set(document) - fields)
    missing = sorted(fields - set(document))
    if unknown:
        raise ValueError("handover policy has unknown fields: " + ", ".join(unknown))
    if missing:
        raise ValueError("handover policy is missing fields: " + ", ".join(missing))

    values = {
        field: _string_tuple(document[field], f"policy {field}") for field in fields
    }
    punch_statuses = {normalize_heading(value) for value in values["punch_statuses"]}
    classified_statuses: set[str] = set()
    for field in (
        "open_punch_statuses",
        "deferred_punch_statuses",
        "closed_punch_statuses",
    ):
        normalized = {normalize_heading(value) for value in values[field]}
        overlap = classified_statuses & normalized
        if overlap:
            raise ValueError(
                "punch status classifications overlap: " + ", ".join(sorted(overlap))
            )
        classified_statuses.update(normalized)
        if not normalized <= punch_statuses:
            raise ValueError(f"policy {field} contains an unknown punch status")
    if classified_statuses != punch_statuses:
        raise ValueError("every punch status must have exactly one classification")

    severities = {normalize_heading(value) for value in values["severities"]}
    for field in ("blocking_severities", "non_deferrable_severities"):
        if not {normalize_heading(value) for value in values[field]} <= severities:
            raise ValueError(f"policy {field} contains an unknown severity")

    accepted_risks = {
        normalize_heading(value) for value in values["accepted_risk_statuses"]
    }
    closed_risks = {
        normalize_heading(value) for value in values["closed_risk_statuses"]
    }
    if accepted_risks & closed_risks:
        raise ValueError("accepted and closed risk statuses must not overlap")

    release = {normalize_heading(value) for value in values["release_decisions"]}
    conditional = {
        normalize_heading(value) for value in values["conditional_decisions"]
    }
    pending = {normalize_heading(value) for value in values["pending_decisions"]}
    if not conditional <= release:
        raise ValueError("conditional decisions must also be release decisions")
    if release & pending:
        raise ValueError("release and pending decisions must not overlap")

    return HandoverPolicy(**values)


def _normalized_aliases(values: Sequence[str]) -> set[str]:
    return {normalize_heading(value) for value in values}


def _column_indices(
    header: Sequence[str], aliases: dict[str, tuple[str, ...]], context: str
) -> dict[str, int]:
    normalized_header = [normalize_heading(value) for value in header]
    indices: dict[str, int] = {}
    for field, candidates in aliases.items():
        matches = [
            index
            for index, column in enumerate(normalized_header)
            if column in _normalized_aliases(candidates)
        ]
        if not matches:
            raise ValueError(
                f"{context}: missing required column for {field}: "
                + ", ".join(candidates)
            )
        if len(matches) > 1:
            raise ValueError(f"{context}: ambiguous columns for {field}")
        indices[field] = matches[0]
    return indices


def _parse_ids(value: str) -> tuple[str, ...]:
    if not value.strip():
        return ()
    return tuple(
        token.strip()
        for token in re.split(r"\s*(?:,|;|<br\s*/?>)\s*", value, flags=re.I)
        if token.strip()
    )


def extract_handover_records(
    path: Path,
) -> tuple[list[PunchItem], list[ResidualRisk], list[AcceptanceDecision]]:
    """Extract the three controlled handover registers from Markdown tables."""

    lines = path.read_text(encoding="utf-8").splitlines()
    if lines and lines[0].strip().startswith("<!-- generated by scripts/"):
        return [], [], []

    punch_items: list[PunchItem] = []
    residual_risks: list[ResidualRisk] = []
    decisions: list[AcceptanceDecision] = []
    for start_line, block in table_blocks(lines):
        if len(block) < 3:
            continue
        header = table_cells(block[0])
        normalized = {normalize_heading(value) for value in header}
        signatures = []
        if {"severity", "finding or nonconformance"} <= normalized:
            signatures.append("punch")
        if {"source item id", "interim control"} <= normalized:
            signatures.append("risk")
        if {"acceptance id", "decision"} <= normalized:
            signatures.append("acceptance")
        if not signatures:
            continue
        context = f"{path}:{start_line}"
        if len(signatures) > 1:
            raise ValueError(f"{context}: handover table type is ambiguous")
        table_type = signatures[0]
        aliases = {
            "punch": PUNCH_COLUMNS,
            "risk": RISK_COLUMNS,
            "acceptance": ACCEPTANCE_COLUMNS,
        }[table_type]
        indices = _column_indices(header, aliases, context)
        for offset, row in enumerate(block[2:], start=2):
            line = start_line + offset
            cells = table_cells(row)
            if len(cells) != len(header):
                raise ValueError(
                    f"{path}:{line}: table row has {len(cells)} cells; "
                    f"expected {len(header)}"
                )
            if not any(cells):
                continue
            common = {"source": path.as_posix(), "line": line}
            if table_type == "punch":
                punch_items.append(
                    PunchItem(
                        **common,
                        **{field: cells[index] for field, index in indices.items()},
                    )
                )
            elif table_type == "risk":
                residual_risks.append(
                    ResidualRisk(
                        **common,
                        **{field: cells[index] for field, index in indices.items()},
                    )
                )
            else:
                values = {field: cells[index] for field, index in indices.items()}
                values["residual_risk_ids"] = _parse_ids(values["residual_risk_ids"])
                decisions.append(AcceptanceDecision(**common, **values))
    return punch_items, residual_risks, decisions


def _normalized(values: Sequence[str]) -> set[str]:
    return {normalize_heading(value) for value in values}


def audit_handover(
    punch_items: Sequence[PunchItem],
    residual_risks: Sequence[ResidualRisk],
    decisions: Sequence[AcceptanceDecision],
    policy: HandoverPolicy,
) -> list[HandoverIssue]:
    """Return cross-register integrity and release-control findings."""

    issues: list[HandoverIssue] = []
    missing_values = _normalized(policy.missing_values)
    severities = _normalized(policy.severities)
    punch_statuses = _normalized(policy.punch_statuses)
    open_statuses = _normalized(policy.open_punch_statuses)
    deferred_statuses = _normalized(policy.deferred_punch_statuses)
    closed_statuses = _normalized(policy.closed_punch_statuses)
    accepted_risk_statuses = _normalized(policy.accepted_risk_statuses)
    closed_risk_statuses = _normalized(policy.closed_risk_statuses)
    release_decisions = _normalized(policy.release_decisions)
    conditional_decisions = _normalized(policy.conditional_decisions)
    pending_decisions = _normalized(policy.pending_decisions)
    blocking_severities = _normalized(policy.blocking_severities)
    non_deferrable = _normalized(policy.non_deferrable_severities)

    def add(record: object, record_id: str, kind: str, detail: str) -> None:
        issues.append(
            HandoverIssue(
                source=getattr(record, "source"),
                line=getattr(record, "line"),
                record_id=record_id or "(blank)",
                kind=kind,
                detail=detail,
            )
        )

    def is_missing(value: str) -> bool:
        return not value.strip() or normalize_heading(value) in missing_values

    def valid_id(value: str) -> bool:
        return bool(IDENTIFIER_PATTERN.fullmatch(value))

    def index_records(
        records: Sequence[object], id_field: str, kind: str
    ) -> dict[str, object]:
        indexed: dict[str, object] = {}
        for record in records:
            record_id = getattr(record, id_field)
            if not valid_id(record_id):
                add(
                    record,
                    record_id,
                    f"invalid_{kind}_id",
                    "ID must be uppercase, hyphenated, and end in digits",
                )
            key = record_id.casefold()
            if key in indexed:
                first = indexed[key]
                add(
                    record,
                    record_id,
                    f"duplicate_{kind}_id",
                    f"first declared at {getattr(first, 'source')}:{getattr(first, 'line')}",
                )
            else:
                indexed[key] = record
        return indexed

    punch_by_id = index_records(punch_items, "item_id", "punch")
    risk_by_id = index_records(residual_risks, "risk_id", "risk")
    index_records(decisions, "acceptance_id", "acceptance")

    risks_by_source: dict[str, list[ResidualRisk]] = {}
    active_risks: dict[str, ResidualRisk] = {}
    for risk in residual_risks:
        for label, value in {
            "source item ID": risk.source_item_id,
            "risk description": risk.description,
            "interim control": risk.interim_control,
            "owner": risk.owner,
            "approval": risk.approval,
            "target close date": risk.target_close_date,
            "status": risk.status,
            "closeout evidence": risk.closeout_evidence,
        }.items():
            if is_missing(value):
                add(risk, risk.risk_id, "missing_risk_field", f"{label} is required")
        if not valid_id(risk.source_item_id):
            add(
                risk,
                risk.risk_id,
                "invalid_source_reference",
                f"invalid source item ID: {risk.source_item_id}",
            )
        source_key = risk.source_item_id.casefold()
        risks_by_source.setdefault(source_key, []).append(risk)
        source = punch_by_id.get(source_key)
        if source is None:
            add(
                risk,
                risk.risk_id,
                "unknown_source_item",
                f"punch-list item is not registered: {risk.source_item_id}",
            )
        risk_status = normalize_heading(risk.status)
        if risk_status not in accepted_risk_statuses | closed_risk_statuses:
            add(
                risk,
                risk.risk_id,
                "unknown_risk_status",
                f"status is not allowed by policy: {risk.status!r}",
            )
        if risk_status in accepted_risk_statuses:
            active_risks[risk.risk_id.casefold()] = risk
            if (
                source is not None
                and normalize_heading(source.status) not in deferred_statuses
            ):
                add(
                    risk,
                    risk.risk_id,
                    "active_risk_source_not_deferred",
                    f"source {source.item_id} has status {source.status!r}",
                )
        if risk_status in closed_risk_statuses and source is not None:
            if normalize_heading(source.status) not in closed_statuses:
                add(
                    risk,
                    risk.risk_id,
                    "closed_risk_source_not_closed",
                    f"source {source.item_id} has status {source.status!r}",
                )

    for item in punch_items:
        for label, value in {
            "finding": item.finding,
            "severity": item.severity,
            "owner": item.owner,
            "target close date": item.target_close_date,
            "status": item.status,
        }.items():
            if is_missing(value):
                add(item, item.item_id, "missing_punch_field", f"{label} is required")
        status = normalize_heading(item.status)
        if normalize_heading(item.severity) not in severities:
            add(
                item,
                item.item_id,
                "unknown_severity",
                f"severity is not allowed by policy: {item.severity!r}",
            )
        if status not in punch_statuses:
            add(
                item,
                item.item_id,
                "unknown_punch_status",
                f"status is not allowed by policy: {item.status!r}",
            )
        linked = risks_by_source.get(item.item_id.casefold(), [])
        if status in deferred_statuses:
            active_linked = [
                risk
                for risk in linked
                if normalize_heading(risk.status) in accepted_risk_statuses
            ]
            if not active_linked:
                add(
                    item,
                    item.item_id,
                    "unapproved_deferral",
                    "deferred item has no accepted residual-risk record",
                )
            if len(active_linked) > 1:
                add(
                    item,
                    item.item_id,
                    "multiple_active_risks",
                    "deferred item has more than one active residual-risk record",
                )
            if normalize_heading(item.severity) in non_deferrable:
                add(
                    item,
                    item.item_id,
                    "non_deferrable_item",
                    f"{item.severity} items cannot be deferred under this policy",
                )
        if status in closed_statuses:
            if is_missing(item.evidence_link):
                add(
                    item,
                    item.item_id,
                    "missing_closeout_evidence",
                    "closed item requires an evidence link",
                )
            if is_missing(item.closeout_note):
                add(
                    item,
                    item.item_id,
                    "missing_closeout_note",
                    "closed item requires a verification or closeout note",
                )

    release_records: list[AcceptanceDecision] = []
    for decision in decisions:
        state = normalize_heading(decision.decision)
        if is_missing(decision.decision):
            add(
                decision,
                decision.acceptance_id,
                "missing_acceptance_field",
                "decision is required",
            )
        if state not in release_decisions | pending_decisions:
            add(
                decision,
                decision.acceptance_id,
                "unknown_acceptance_decision",
                f"decision is not allowed by policy: {decision.decision!r}",
            )
        if state in release_decisions:
            release_records.append(decision)
            for label, value in {
                "approved by": decision.approved_by,
                "approval date": decision.approval_date,
                "evidence location": decision.evidence_location,
            }.items():
                if is_missing(value):
                    add(
                        decision,
                        decision.acceptance_id,
                        "missing_acceptance_field",
                        f"{label} is required for a release decision",
                    )

        seen: set[str] = set()
        for risk_id in decision.residual_risk_ids:
            key = risk_id.casefold()
            if not valid_id(risk_id):
                add(
                    decision,
                    decision.acceptance_id,
                    "invalid_risk_reference",
                    f"invalid residual-risk ID: {risk_id}",
                )
            if key in seen:
                add(
                    decision,
                    decision.acceptance_id,
                    "duplicate_risk_reference",
                    f"residual-risk ID is repeated: {risk_id}",
                )
            seen.add(key)
            if key not in risk_by_id:
                add(
                    decision,
                    decision.acceptance_id,
                    "unknown_risk_reference",
                    f"residual-risk ID is not registered: {risk_id}",
                )
            elif key not in active_risks:
                add(
                    decision,
                    decision.acceptance_id,
                    "inactive_risk_reference",
                    f"residual-risk ID is not active: {risk_id}",
                )

        if state in conditional_decisions:
            referenced = {value.casefold() for value in decision.residual_risk_ids}
            for key, risk in active_risks.items():
                if key not in referenced:
                    add(
                        decision,
                        decision.acceptance_id,
                        "unlisted_residual_risk",
                        f"active residual risk is omitted: {risk.risk_id}",
                    )
        elif state in release_decisions and active_risks:
            add(
                decision,
                decision.acceptance_id,
                "unconditional_acceptance_with_deferrals",
                "unconditional acceptance cannot have active residual risks",
            )

        if state in release_decisions:
            for item in punch_items:
                if (
                    normalize_heading(item.status) in open_statuses
                    and normalize_heading(item.severity) in blocking_severities
                ):
                    add(
                        decision,
                        decision.acceptance_id,
                        "acceptance_blocker",
                        f"{item.severity} item {item.item_id} remains {item.status!r}",
                    )

    if len(release_records) > 1:
        for decision in release_records[1:]:
            add(
                decision,
                decision.acceptance_id,
                "multiple_release_decisions",
                f"release already declared by {release_records[0].acceptance_id}",
            )
    return issues


def summarize_handover(
    punch_items: Sequence[PunchItem],
    residual_risks: Sequence[ResidualRisk],
    decisions: Sequence[AcceptanceDecision],
    issues: Sequence[HandoverIssue],
    policy: HandoverPolicy,
) -> dict[str, object]:
    deferred = _normalized(policy.deferred_punch_statuses)
    active = _normalized(policy.accepted_risk_statuses)
    return {
        "source_files": sorted(
            {record.source for record in [*punch_items, *residual_risks, *decisions]}
        ),
        "punch_item_count": len(punch_items),
        "deferred_item_count": sum(
            normalize_heading(item.status) in deferred for item in punch_items
        ),
        "residual_risk_count": len(residual_risks),
        "active_residual_risk_count": sum(
            normalize_heading(risk.status) in active for risk in residual_risks
        ),
        "acceptance_decision_count": len(decisions),
        "issue_count": len(issues),
        "punch_items": [asdict(item) for item in punch_items],
        "residual_risks": [asdict(risk) for risk in residual_risks],
        "acceptance_decisions": [asdict(decision) for decision in decisions],
        "issues": [asdict(issue) for issue in issues],
    }


def _markdown_cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_markdown(summary: dict[str, object]) -> str:
    lines = [
        GENERATED_MARKER,
        "<!-- markdownlint-disable MD013 -->",
        "",
        "# Handover Acceptance Audit",
        "",
        f"Source files: {len(summary['source_files'])}  ",
        f"Punch-list items: {summary['punch_item_count']}  ",
        f"Deferred items: {summary['deferred_item_count']}  ",
        f"Residual risks: {summary['residual_risk_count']}  ",
        f"Acceptance decisions: {summary['acceptance_decision_count']}  ",
        f"Issues: {summary['issue_count']}",
    ]
    if summary["issues"]:
        lines.extend(
            [
                "",
                "## Issues",
                "",
                "| Source | Line | Record | Kind | Detail |",
                "| --- | ---: | --- | --- | --- |",
            ]
        )
        lines.extend(
            "| {source} | {line} | {record_id} | {kind} | {detail} |".format(
                **{key: _markdown_cell(value) for key, value in issue.items()}
            )
            for issue in summary["issues"]
        )
    lines.extend(
        [
            "",
            "## Punch-List Items",
            "",
            "| Source | Line | Item ID | Severity | Status |",
            "| --- | ---: | --- | --- | --- |",
        ]
    )
    lines.extend(
        "| {source} | {line} | {item_id} | {severity} | {status} |".format(
            **{key: _markdown_cell(value) for key, value in record.items()}
        )
        for record in summary["punch_items"]
    )
    lines.extend(
        [
            "",
            "## Residual-Risk Register",
            "",
            "| Source | Line | Risk ID | Source Item ID | Status |",
            "| --- | ---: | --- | --- | --- |",
        ]
    )
    lines.extend(
        "| {source} | {line} | {risk_id} | {source_item_id} | {status} |".format(
            **{key: _markdown_cell(value) for key, value in record.items()}
        )
        for record in summary["residual_risks"]
    )
    lines.extend(
        [
            "",
            "## Acceptance Decisions",
            "",
            "| Acceptance ID | Decision | Residual-Risk IDs | Approved By |",
            "| --- | --- | --- | --- |",
        ]
    )
    lines.extend(
        "| {acceptance_id} | {decision} | {risk_ids} | {approved_by} |".format(
            acceptance_id=_markdown_cell(record["acceptance_id"]),
            decision=_markdown_cell(record["decision"]),
            risk_ids=_markdown_cell(", ".join(record["residual_risk_ids"])),
            approved_by=_markdown_cell(record["approved_by"]),
        )
        for record in summary["acceptance_decisions"]
    )
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Cross-check punch-list, residual-risk, and acceptance records."
    )
    parser.add_argument("paths", nargs="*", type=Path)
    parser.add_argument(
        "--policy",
        type=Path,
        default=Path("config/handover-acceptance-policy.example.json"),
    )
    parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    parser.add_argument("--output", type=Path)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        policy = load_handover_policy(args.policy)
        inputs = args.paths or [Path("examples/handover-acceptance-passing.md")]
        paths = expand_paths(inputs)
        punch_items: list[PunchItem] = []
        residual_risks: list[ResidualRisk] = []
        decisions: list[AcceptanceDecision] = []
        for path in paths:
            path_punch, path_risks, path_decisions = extract_handover_records(path)
            punch_items.extend(path_punch)
            residual_risks.extend(path_risks)
            decisions.extend(path_decisions)
        if not punch_items:
            raise ValueError("no punch-list rows found")
        if not residual_risks:
            raise ValueError("no residual-risk rows found")
        if not decisions:
            raise ValueError("no acceptance-decision rows found")
        issues = audit_handover(punch_items, residual_risks, decisions, policy)
    except (json.JSONDecodeError, OSError, ValueError) as error:
        print(f"Handover acceptance audit failed: {error}", file=sys.stderr)
        return 1

    summary = summarize_handover(punch_items, residual_risks, decisions, issues, policy)
    rendered = (
        json.dumps(summary, indent=2) + "\n"
        if args.format == "json"
        else render_markdown(summary)
    )
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    else:
        print(rendered, end="")

    for issue in issues:
        print(
            f"{issue.source}:{issue.line}: {issue.record_id}: "
            f"{issue.kind}: {issue.detail}",
            file=sys.stderr,
        )
    if issues:
        print(
            f"Handover acceptance gate failed with {len(issues)} issue(s).",
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
