from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path
from typing import Sequence

try:
    from scripts.summarize_status import expand_paths, normalize_heading
    from scripts.validate_templates import table_blocks, table_cells
except ModuleNotFoundError:
    from summarize_status import expand_paths, normalize_heading
    from validate_templates import table_blocks, table_cells


GENERATED_MARKER = "<!-- generated by scripts/audit_calibration_traceability.py -->"
IDENTIFIER_PATTERN = re.compile(r"^[A-Z][A-Z0-9]*(?:-[A-Z0-9]+)*-\d+$")
DEFAULT_COMPLETED_STATUSES = (
    "Complete",
    "Completed",
    "Accepted",
    "Ready for verification",
)
DEFAULT_ACCEPTED_CALIBRATION_STATUSES = ("Approved", "Valid", "Accepted")
DEFAULT_MISSING_VALUES = ("TBD", "TBC", "N/A", "NA", "-")

MEASUREMENT_COLUMNS = {
    "measurement_id": ("Measurement ID", "Test Measurement ID"),
    "check_id": ("Check ID", "Test ID", "Requirement ID"),
    "item": ("Measurement or Test", "Check or Test", "Measurement"),
    "instrument_ids": ("Instrument IDs", "Instrument ID"),
    "test_date": ("Test Date", "Execution Date"),
    "owner": ("Owner", "Responsible Owner"),
    "status": ("Status", "Measurement Status"),
}
CALIBRATION_COLUMNS = {
    "calibration_id": ("Calibration ID", "Certificate ID"),
    "instrument_id": ("Instrument ID",),
    "valid_from": ("Valid From", "Calibration Start"),
    "valid_through": ("Valid Through", "Calibration Expiry"),
    "approval_status": ("Approval Status", "Calibration Status"),
    "certificate_location": ("Certificate Location", "Controlled Location"),
}


@dataclass(frozen=True)
class MeasurementRecord:
    source: str
    line: int
    measurement_id: str
    check_id: str
    item: str
    instrument_ids: tuple[str, ...]
    test_date: str
    owner: str
    status: str


@dataclass(frozen=True)
class CalibrationRecord:
    source: str
    line: int
    calibration_id: str
    instrument_id: str
    valid_from: str
    valid_through: str
    approval_status: str
    certificate_location: str


@dataclass(frozen=True)
class CalibrationIssue:
    source: str
    line: int
    record_id: str
    kind: str
    detail: str


def _normalized_aliases(aliases: Sequence[str]) -> set[str]:
    return {normalize_heading(alias) for alias in aliases}


def _column_indices(
    header: Sequence[str],
    aliases_by_field: dict[str, tuple[str, ...]],
    context: str,
) -> dict[str, int]:
    normalized_header = [normalize_heading(value) for value in header]
    indices: dict[str, int] = {}
    for field, aliases in aliases_by_field.items():
        matches = [
            index
            for index, column in enumerate(normalized_header)
            if column in _normalized_aliases(aliases)
        ]
        if not matches:
            raise ValueError(
                f"{context}: missing required column for {field}: "
                + ", ".join(aliases)
            )
        if len(matches) > 1:
            columns = ", ".join(header[index] for index in matches)
            raise ValueError(f"{context}: ambiguous {field} columns: {columns}")
        indices[field] = matches[0]
    return indices


def _parse_identifiers(value: str) -> tuple[str, ...]:
    if not value.strip():
        return ()
    return tuple(
        token.strip()
        for token in re.split(r"\s*(?:,|;|<br\s*/?>)\s*", value, flags=re.I)
        if token.strip()
    )


def _unique_identifiers(values: Sequence[str]) -> tuple[str, ...]:
    unique: list[str] = []
    seen: set[str] = set()
    for value in values:
        normalized = value.casefold()
        if normalized not in seen:
            seen.add(normalized)
            unique.append(value)
    return tuple(unique)


def extract_calibration_records(
    path: Path,
) -> tuple[list[MeasurementRecord], list[CalibrationRecord]]:
    """Extract measurement use and instrument calibration history tables."""

    lines = path.read_text(encoding="utf-8").splitlines()
    if lines and lines[0].strip() == GENERATED_MARKER:
        return [], []

    measurement_id_aliases = _normalized_aliases(
        MEASUREMENT_COLUMNS["measurement_id"]
    )
    calibration_id_aliases = _normalized_aliases(
        CALIBRATION_COLUMNS["calibration_id"]
    )
    valid_through_aliases = _normalized_aliases(
        CALIBRATION_COLUMNS["valid_through"]
    )
    measurements: list[MeasurementRecord] = []
    calibrations: list[CalibrationRecord] = []
    for start_line, block in table_blocks(lines):
        if len(block) < 3:
            continue
        header = table_cells(block[0])
        normalized_header = {normalize_heading(value) for value in header}
        is_measurement_table = bool(normalized_header & measurement_id_aliases)
        is_calibration_table = bool(
            normalized_header & calibration_id_aliases
            and normalized_header & valid_through_aliases
        )
        if not is_measurement_table and not is_calibration_table:
            continue
        if is_measurement_table and is_calibration_table:
            raise ValueError(
                f"{path}:{start_line}: table matches both measurement and "
                "calibration schemas"
            )

        context = f"{path}:{start_line}"
        aliases = (
            MEASUREMENT_COLUMNS if is_measurement_table else CALIBRATION_COLUMNS
        )
        indices = _column_indices(header, aliases, context)
        for offset, row in enumerate(block[2:], start=2):
            row_line = start_line + offset
            cells = table_cells(row)
            if len(cells) != len(header):
                raise ValueError(
                    f"{path}:{row_line}: table row has {len(cells)} cells; "
                    f"expected {len(header)}"
                )
            if not any(cells):
                continue
            if is_measurement_table:
                measurements.append(
                    MeasurementRecord(
                        source=path.as_posix(),
                        line=row_line,
                        measurement_id=cells[indices["measurement_id"]],
                        check_id=cells[indices["check_id"]],
                        item=cells[indices["item"]] or f"Row {row_line}",
                        instrument_ids=_parse_identifiers(
                            cells[indices["instrument_ids"]]
                        ),
                        test_date=cells[indices["test_date"]],
                        owner=cells[indices["owner"]],
                        status=cells[indices["status"]],
                    )
                )
            else:
                calibrations.append(
                    CalibrationRecord(
                        source=path.as_posix(),
                        line=row_line,
                        calibration_id=cells[indices["calibration_id"]],
                        instrument_id=cells[indices["instrument_id"]],
                        valid_from=cells[indices["valid_from"]],
                        valid_through=cells[indices["valid_through"]],
                        approval_status=cells[indices["approval_status"]],
                        certificate_location=cells[indices["certificate_location"]],
                    )
                )
    return measurements, calibrations


def _is_missing(value: str, missing_values: set[str]) -> bool:
    return not value.strip() or normalize_heading(value) in missing_values


def _identifier_is_valid(value: str) -> bool:
    return bool(IDENTIFIER_PATTERN.fullmatch(value))


def _iso_date(value: str) -> date | None:
    try:
        parsed = date.fromisoformat(value)
    except ValueError:
        return None
    return parsed if parsed.isoformat() == value else None


def audit_calibration_traceability(
    measurements: Sequence[MeasurementRecord],
    calibrations: Sequence[CalibrationRecord],
    *,
    completed_statuses: Sequence[str] = DEFAULT_COMPLETED_STATUSES,
    accepted_calibration_statuses: Sequence[
        str
    ] = DEFAULT_ACCEPTED_CALIBRATION_STATUSES,
    missing_values: Sequence[str] = DEFAULT_MISSING_VALUES,
) -> list[CalibrationIssue]:
    """Return identifier, calibration-period, and completed-test issues."""

    completed = {normalize_heading(value) for value in completed_statuses}
    accepted = {
        normalize_heading(value) for value in accepted_calibration_statuses
    }
    missing = {normalize_heading(value) for value in missing_values}
    issues: list[CalibrationIssue] = []

    def add_issue(
        source: str,
        line: int,
        record_id: str,
        kind: str,
        detail: str,
    ) -> None:
        issues.append(
            CalibrationIssue(
                source=source,
                line=line,
                record_id=record_id or "(blank)",
                kind=kind,
                detail=detail,
            )
        )

    measurement_ids: dict[str, MeasurementRecord] = {}
    measurement_dates: dict[MeasurementRecord, date] = {}
    for measurement in measurements:
        normalized_id = measurement.measurement_id.casefold()
        if not _identifier_is_valid(measurement.measurement_id):
            add_issue(
                measurement.source,
                measurement.line,
                measurement.measurement_id,
                "invalid_measurement_id",
                "measurement ID must be uppercase, hyphenated, and end in digits",
            )
        if normalized_id in measurement_ids:
            first = measurement_ids[normalized_id]
            add_issue(
                measurement.source,
                measurement.line,
                measurement.measurement_id,
                "duplicate_measurement_id",
                f"first declared at {first.source}:{first.line}",
            )
        else:
            measurement_ids[normalized_id] = measurement

        fields = {
            "check ID": measurement.check_id,
            "measurement or test": measurement.item,
            "test date": measurement.test_date,
            "owner": measurement.owner,
            "status": measurement.status,
        }
        for label, value in fields.items():
            if _is_missing(value, missing):
                add_issue(
                    measurement.source,
                    measurement.line,
                    measurement.measurement_id,
                    "missing_measurement_field",
                    f"{label} is required",
                )
        if not _is_missing(measurement.check_id, missing) and not _identifier_is_valid(
            measurement.check_id
        ):
            add_issue(
                measurement.source,
                measurement.line,
                measurement.measurement_id,
                "invalid_check_id",
                f"invalid check ID: {measurement.check_id}",
            )
        if not measurement.instrument_ids:
            add_issue(
                measurement.source,
                measurement.line,
                measurement.measurement_id,
                "missing_instrument_reference",
                "at least one instrument ID is required",
            )
        seen_instruments: set[str] = set()
        for instrument_id in measurement.instrument_ids:
            normalized_instrument = instrument_id.casefold()
            if not _identifier_is_valid(instrument_id):
                add_issue(
                    measurement.source,
                    measurement.line,
                    measurement.measurement_id,
                    "invalid_instrument_reference",
                    f"invalid instrument ID: {instrument_id}",
                )
            if normalized_instrument in seen_instruments:
                add_issue(
                    measurement.source,
                    measurement.line,
                    measurement.measurement_id,
                    "duplicate_instrument_reference",
                    f"instrument ID is repeated in the row: {instrument_id}",
                )
            seen_instruments.add(normalized_instrument)

        if not _is_missing(measurement.test_date, missing):
            parsed_test_date = _iso_date(measurement.test_date)
            if parsed_test_date is None:
                add_issue(
                    measurement.source,
                    measurement.line,
                    measurement.measurement_id,
                    "invalid_test_date",
                    "test date must use YYYY-MM-DD",
                )
            else:
                measurement_dates[measurement] = parsed_test_date

    calibration_ids: dict[str, CalibrationRecord] = {}
    calibration_periods: dict[CalibrationRecord, tuple[date, date]] = {}
    calibrations_by_instrument: dict[str, list[CalibrationRecord]] = defaultdict(list)
    for calibration in calibrations:
        normalized_id = calibration.calibration_id.casefold()
        if not _identifier_is_valid(calibration.calibration_id):
            add_issue(
                calibration.source,
                calibration.line,
                calibration.calibration_id,
                "invalid_calibration_id",
                "calibration ID must be uppercase, hyphenated, and end in digits",
            )
        if normalized_id in calibration_ids:
            first = calibration_ids[normalized_id]
            add_issue(
                calibration.source,
                calibration.line,
                calibration.calibration_id,
                "duplicate_calibration_id",
                f"first declared at {first.source}:{first.line}",
            )
        else:
            calibration_ids[normalized_id] = calibration

        if not _identifier_is_valid(calibration.instrument_id):
            add_issue(
                calibration.source,
                calibration.line,
                calibration.calibration_id,
                "invalid_instrument_id",
                f"invalid instrument ID: {calibration.instrument_id}",
            )
        fields = {
            "instrument ID": calibration.instrument_id,
            "valid from": calibration.valid_from,
            "valid through": calibration.valid_through,
            "approval status": calibration.approval_status,
            "certificate location": calibration.certificate_location,
        }
        for label, value in fields.items():
            if _is_missing(value, missing):
                add_issue(
                    calibration.source,
                    calibration.line,
                    calibration.calibration_id,
                    "missing_calibration_field",
                    f"{label} is required",
                )

        start = (
            None
            if _is_missing(calibration.valid_from, missing)
            else _iso_date(calibration.valid_from)
        )
        end = (
            None
            if _is_missing(calibration.valid_through, missing)
            else _iso_date(calibration.valid_through)
        )
        if start is None and not _is_missing(calibration.valid_from, missing):
            add_issue(
                calibration.source,
                calibration.line,
                calibration.calibration_id,
                "invalid_valid_from",
                "valid-from date must use YYYY-MM-DD",
            )
        if end is None and not _is_missing(calibration.valid_through, missing):
            add_issue(
                calibration.source,
                calibration.line,
                calibration.calibration_id,
                "invalid_valid_through",
                "valid-through date must use YYYY-MM-DD",
            )
        if start is not None and end is not None:
            if start > end:
                add_issue(
                    calibration.source,
                    calibration.line,
                    calibration.calibration_id,
                    "invalid_calibration_period",
                    "valid-from date must not be after valid-through date",
                )
            else:
                calibration_periods[calibration] = (start, end)
        calibrations_by_instrument[calibration.instrument_id.casefold()].append(
            calibration
        )

    for measurement in measurements:
        is_completed = normalize_heading(measurement.status) in completed
        test_date = measurement_dates.get(measurement)
        for instrument_id in _unique_identifiers(measurement.instrument_ids):
            history = calibrations_by_instrument.get(instrument_id.casefold(), [])
            if not history:
                add_issue(
                    measurement.source,
                    measurement.line,
                    measurement.measurement_id,
                    "unknown_instrument_reference",
                    f"instrument ID is not registered: {instrument_id}",
                )
                continue
            if not is_completed or test_date is None:
                continue
            covering = [
                calibration
                for calibration in history
                if calibration in calibration_periods
                and calibration_periods[calibration][0] <= test_date
                <= calibration_periods[calibration][1]
            ]
            if not covering:
                add_issue(
                    measurement.source,
                    measurement.line,
                    measurement.measurement_id,
                    "no_calibration_at_test_date",
                    f"{instrument_id} has no calibration covering "
                    f"{measurement.test_date}",
                )
                continue
            if len(covering) > 1:
                identifiers = ", ".join(
                    calibration.calibration_id for calibration in covering
                )
                add_issue(
                    measurement.source,
                    measurement.line,
                    measurement.measurement_id,
                    "overlapping_calibrations",
                    f"{instrument_id} has multiple calibrations covering "
                    f"{measurement.test_date}: {identifiers}",
                )
                continue
            calibration = covering[0]
            if normalize_heading(calibration.approval_status) not in accepted:
                add_issue(
                    measurement.source,
                    measurement.line,
                    measurement.measurement_id,
                    "unaccepted_calibration",
                    f"{calibration.calibration_id} for {instrument_id} has "
                    f"approval status {calibration.approval_status!r}",
                )
    return issues


def _covering_calibration_ids(
    measurement: MeasurementRecord,
    calibrations: Sequence[CalibrationRecord],
) -> list[str]:
    test_date = _iso_date(measurement.test_date)
    if test_date is None:
        return []
    instruments = {value.casefold() for value in measurement.instrument_ids}
    covering: list[str] = []
    for calibration in calibrations:
        if calibration.instrument_id.casefold() not in instruments:
            continue
        start = _iso_date(calibration.valid_from)
        end = _iso_date(calibration.valid_through)
        if start is not None and end is not None and start <= test_date <= end:
            covering.append(calibration.calibration_id)
    return covering


def summarize_calibration_traceability(
    measurements: Sequence[MeasurementRecord],
    calibrations: Sequence[CalibrationRecord],
    issues: Sequence[CalibrationIssue],
    completed_statuses: Sequence[str] = DEFAULT_COMPLETED_STATUSES,
) -> dict[str, object]:
    completed = {normalize_heading(value) for value in completed_statuses}
    references: dict[str, list[str]] = defaultdict(list)
    measurement_items = []
    for measurement in measurements:
        for instrument_id in _unique_identifiers(measurement.instrument_ids):
            references[instrument_id.casefold()].append(measurement.measurement_id)
        item = asdict(measurement)
        item["covering_calibration_ids"] = _covering_calibration_ids(
            measurement,
            calibrations,
        )
        measurement_items.append(item)
    calibration_items = []
    for calibration in calibrations:
        item = asdict(calibration)
        item["instrument_used_by"] = references.get(
            calibration.instrument_id.casefold(), []
        )
        calibration_items.append(item)
    return {
        "source_files": sorted(
            {record.source for record in [*measurements, *calibrations]}
        ),
        "measurement_count": len(measurements),
        "completed_measurement_count": sum(
            normalize_heading(measurement.status) in completed
            for measurement in measurements
        ),
        "calibration_record_count": len(calibrations),
        "instrument_count": len(
            {calibration.instrument_id.casefold() for calibration in calibrations}
        ),
        "issue_count": len(issues),
        "measurements": measurement_items,
        "calibrations": calibration_items,
        "issues": [asdict(issue) for issue in issues],
    }


def _markdown_cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_markdown(summary: dict[str, object]) -> str:
    lines = [
        GENERATED_MARKER,
        "<!-- markdownlint-disable MD013 -->",
        "",
        "# Instrument Calibration Traceability Audit",
        "",
        f"Source files: {len(summary['source_files'])}  ",
        f"Measurements: {summary['measurement_count']}  ",
        f"Completed measurements: {summary['completed_measurement_count']}  ",
        f"Calibration records: {summary['calibration_record_count']}  ",
        f"Instruments: {summary['instrument_count']}  ",
        f"Issues: {summary['issue_count']}",
    ]
    issues = summary["issues"]
    if issues:
        lines.extend(
            [
                "",
                "## Issues",
                "",
                "| Source | Line | Record | Kind | Detail |",
                "| --- | ---: | --- | --- | --- |",
            ]
        )
        lines.extend(
            "| {source} | {line} | {record_id} | {kind} | {detail} |".format(
                **{key: _markdown_cell(value) for key, value in issue.items()}
            )
            for issue in issues
        )
    lines.extend(
        [
            "",
            "## Measurement Coverage",
            "",
            "| Measurement ID | Check ID | Test Date | Status | "
            "Instrument IDs | Covering Calibrations |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    lines.extend(
        "| {measurement_id} | {check_id} | {test_date} | {status} | "
        "{instrument_ids} | {covering_calibration_ids} |".format(
            measurement_id=_markdown_cell(record["measurement_id"]),
            check_id=_markdown_cell(record["check_id"]),
            test_date=_markdown_cell(record["test_date"]),
            status=_markdown_cell(record["status"]),
            instrument_ids=_markdown_cell(", ".join(record["instrument_ids"])),
            covering_calibration_ids=_markdown_cell(
                ", ".join(record["covering_calibration_ids"])
            ),
        )
        for record in summary["measurements"]
    )
    lines.extend(
        [
            "",
            "## Calibration History",
            "",
            "| Calibration ID | Instrument ID | Valid From | Valid Through | "
            "Approval Status | Instrument Used By | Certificate Location |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    lines.extend(
        "| {calibration_id} | {instrument_id} | {valid_from} | "
        "{valid_through} | {approval_status} | {instrument_used_by} | "
        "{certificate_location} |".format(
            calibration_id=_markdown_cell(record["calibration_id"]),
            instrument_id=_markdown_cell(record["instrument_id"]),
            valid_from=_markdown_cell(record["valid_from"]),
            valid_through=_markdown_cell(record["valid_through"]),
            approval_status=_markdown_cell(record["approval_status"]),
            instrument_used_by=_markdown_cell(
                ", ".join(record["instrument_used_by"])
            ),
            certificate_location=_markdown_cell(record["certificate_location"]),
        )
        for record in summary["calibrations"]
    )
    return "\n".join(lines) + "\n"


def _option_values(
    values: Sequence[str] | None,
    defaults: Sequence[str],
    context: str,
) -> tuple[str, ...]:
    selected = tuple(
        defaults if values is None else (value.strip() for value in values)
    )
    if not selected or any(not value for value in selected):
        raise ValueError(f"{context} must contain nonempty values")
    normalized = [normalize_heading(value) for value in selected]
    if len(normalized) != len(set(normalized)):
        raise ValueError(f"{context} contains case-insensitive duplicates")
    return selected


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Audit completed measurements against instrument calibration history."
        )
    )
    parser.add_argument("paths", nargs="*", type=Path)
    parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    parser.add_argument("--output", type=Path)
    parser.add_argument(
        "--completed-status",
        action="append",
        help=(
            "measurement status requiring valid calibration; repeat to replace "
            "defaults"
        ),
    )
    parser.add_argument(
        "--accepted-calibration-status",
        action="append",
        help="accepted calibration state; repeat to replace defaults",
    )
    parser.add_argument(
        "--missing-value",
        action="append",
        help="controlled missing marker; repeat to replace defaults",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        completed_statuses = _option_values(
            args.completed_status,
            DEFAULT_COMPLETED_STATUSES,
            "completed statuses",
        )
        accepted_statuses = _option_values(
            args.accepted_calibration_status,
            DEFAULT_ACCEPTED_CALIBRATION_STATUSES,
            "accepted calibration statuses",
        )
        missing_values = _option_values(
            args.missing_value,
            DEFAULT_MISSING_VALUES,
            "missing values",
        )
        inputs = args.paths or [Path("examples/calibration-traceability-passing.md")]
        paths = expand_paths(inputs)
        measurements: list[MeasurementRecord] = []
        calibrations: list[CalibrationRecord] = []
        for path in paths:
            path_measurements, path_calibrations = extract_calibration_records(path)
            measurements.extend(path_measurements)
            calibrations.extend(path_calibrations)
        if not measurements:
            raise ValueError("no measurement-use rows found")
        if not calibrations:
            raise ValueError("no calibration-history rows found")
        issues = audit_calibration_traceability(
            measurements,
            calibrations,
            completed_statuses=completed_statuses,
            accepted_calibration_statuses=accepted_statuses,
            missing_values=missing_values,
        )
    except (OSError, ValueError) as error:
        print(f"Calibration traceability audit failed: {error}", file=sys.stderr)
        return 1

    summary = summarize_calibration_traceability(
        measurements,
        calibrations,
        issues,
        completed_statuses,
    )
    rendered = (
        json.dumps(summary, indent=2) + "\n"
        if args.format == "json"
        else render_markdown(summary)
    )
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    else:
        print(rendered, end="")

    for issue in issues:
        print(
            f"{issue.source}:{issue.line}: {issue.record_id}: "
            f"{issue.kind}: {issue.detail}",
            file=sys.stderr,
        )
    if issues:
        print(
            f"Calibration traceability gate failed with {len(issues)} issue(s).",
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
