from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Sequence

try:
    from scripts.summarize_status import expand_paths, normalize_heading
    from scripts.validate_templates import table_blocks, table_cells
except ModuleNotFoundError:
    from summarize_status import expand_paths, normalize_heading
    from validate_templates import table_blocks, table_cells


GENERATED_MARKER = "<!-- generated by scripts/audit_evidence_traceability.py -->"
IDENTIFIER_PATTERN = re.compile(r"^[A-Z][A-Z0-9]*(?:-[A-Z0-9]+)*-\d+$")
DEFAULT_COMPLETED_STATUSES = (
    "Ready for verification",
    "Closed",
    "Accepted",
)
DEFAULT_ACCEPTED_EVIDENCE_STATUSES = ("Approved", "Accepted")
DEFAULT_MISSING_VALUES = ("TBD", "TBC", "N/A", "NA", "-")

CHECK_COLUMNS = {
    "check_id": ("Check ID", "Requirement ID", "Test ID"),
    "item": ("Check or Test", "Requirement", "Test"),
    "evidence_ids": ("Evidence IDs", "Evidence ID"),
    "acceptance_reference": (
        "Acceptance Reference",
        "Acceptance Criterion",
    ),
    "owner": ("Owner", "Responsible Owner"),
    "status": ("Status", "Check Status"),
}
EVIDENCE_COLUMNS = {
    "evidence_id": ("Evidence ID",),
    "location": ("Evidence Location", "Controlled Location"),
    "revision": ("Revision", "Evidence Revision"),
    "approval_status": ("Approval Status", "Evidence Status"),
}


@dataclass(frozen=True)
class CheckRecord:
    source: str
    line: int
    check_id: str
    item: str
    evidence_ids: tuple[str, ...]
    acceptance_reference: str
    owner: str
    status: str


@dataclass(frozen=True)
class EvidenceRecord:
    source: str
    line: int
    evidence_id: str
    location: str
    revision: str
    approval_status: str


@dataclass(frozen=True)
class TraceabilityIssue:
    source: str
    line: int
    record_id: str
    kind: str
    detail: str


def _normalized_aliases(aliases: Sequence[str]) -> set[str]:
    return {normalize_heading(alias) for alias in aliases}


def _column_indices(
    header: Sequence[str],
    aliases_by_field: dict[str, tuple[str, ...]],
    context: str,
) -> dict[str, int]:
    normalized_header = [normalize_heading(value) for value in header]
    indices: dict[str, int] = {}
    for field, aliases in aliases_by_field.items():
        normalized_aliases = _normalized_aliases(aliases)
        matches = [
            index
            for index, column in enumerate(normalized_header)
            if column in normalized_aliases
        ]
        if not matches:
            raise ValueError(
                f"{context}: missing required column for {field}: " + ", ".join(aliases)
            )
        if len(matches) > 1:
            columns = ", ".join(header[index] for index in matches)
            raise ValueError(f"{context}: ambiguous {field} columns: {columns}")
        indices[field] = matches[0]
    return indices


def _parse_evidence_ids(value: str) -> tuple[str, ...]:
    if not value.strip():
        return ()
    return tuple(
        token.strip()
        for token in re.split(r"\s*(?:,|;|<br\s*/?>)\s*", value, flags=re.I)
        if token.strip()
    )


def _unique_evidence_ids(values: Sequence[str]) -> tuple[str, ...]:
    unique: list[str] = []
    seen: set[str] = set()
    for value in values:
        normalized = value.casefold()
        if normalized not in seen:
            seen.add(normalized)
            unique.append(value)
    return tuple(unique)


def extract_traceability_records(
    path: Path,
) -> tuple[list[CheckRecord], list[EvidenceRecord]]:
    """Extract commissioning checks and their controlled evidence register."""

    lines = path.read_text(encoding="utf-8").splitlines()
    if lines and lines[0].strip() == GENERATED_MARKER:
        return [], []

    check_id_aliases = _normalized_aliases(CHECK_COLUMNS["check_id"])
    evidence_location_aliases = _normalized_aliases(EVIDENCE_COLUMNS["location"])
    evidence_id_aliases = _normalized_aliases(EVIDENCE_COLUMNS["evidence_id"])
    checks: list[CheckRecord] = []
    evidence: list[EvidenceRecord] = []
    for start_line, block in table_blocks(lines):
        if len(block) < 3:
            continue
        header = table_cells(block[0])
        normalized_header = {normalize_heading(value) for value in header}
        is_check_table = bool(normalized_header & check_id_aliases)
        is_evidence_table = bool(
            normalized_header & evidence_location_aliases
            and normalized_header & evidence_id_aliases
        )
        if not is_check_table and not is_evidence_table:
            continue

        context = f"{path}:{start_line}"
        aliases = CHECK_COLUMNS if is_check_table else EVIDENCE_COLUMNS
        indices = _column_indices(header, aliases, context)
        for offset, row in enumerate(block[2:], start=2):
            row_line = start_line + offset
            cells = table_cells(row)
            if len(cells) != len(header):
                raise ValueError(
                    f"{path}:{row_line}: table row has {len(cells)} cells; "
                    f"expected {len(header)}"
                )
            if not any(cells):
                continue
            if is_check_table:
                checks.append(
                    CheckRecord(
                        source=path.as_posix(),
                        line=row_line,
                        check_id=cells[indices["check_id"]],
                        item=cells[indices["item"]] or f"Row {row_line}",
                        evidence_ids=_parse_evidence_ids(
                            cells[indices["evidence_ids"]]
                        ),
                        acceptance_reference=cells[indices["acceptance_reference"]],
                        owner=cells[indices["owner"]],
                        status=cells[indices["status"]],
                    )
                )
            else:
                evidence.append(
                    EvidenceRecord(
                        source=path.as_posix(),
                        line=row_line,
                        evidence_id=cells[indices["evidence_id"]],
                        location=cells[indices["location"]],
                        revision=cells[indices["revision"]],
                        approval_status=cells[indices["approval_status"]],
                    )
                )
    return checks, evidence


def _is_missing(value: str, missing_values: set[str]) -> bool:
    return not value.strip() or normalize_heading(value) in missing_values


def _identifier_is_valid(value: str) -> bool:
    return bool(IDENTIFIER_PATTERN.fullmatch(value))


def audit_traceability(
    checks: Sequence[CheckRecord],
    evidence: Sequence[EvidenceRecord],
    *,
    completed_statuses: Sequence[str] = DEFAULT_COMPLETED_STATUSES,
    accepted_evidence_statuses: Sequence[str] = DEFAULT_ACCEPTED_EVIDENCE_STATUSES,
    missing_values: Sequence[str] = DEFAULT_MISSING_VALUES,
) -> list[TraceabilityIssue]:
    """Return identifier, reference, metadata, and acceptance issues."""

    completed = {normalize_heading(value) for value in completed_statuses}
    accepted = {normalize_heading(value) for value in accepted_evidence_statuses}
    missing = {normalize_heading(value) for value in missing_values}
    issues: list[TraceabilityIssue] = []

    def add_issue(
        source: str,
        line: int,
        record_id: str,
        kind: str,
        detail: str,
    ) -> None:
        issues.append(
            TraceabilityIssue(
                source=source,
                line=line,
                record_id=record_id or "(blank)",
                kind=kind,
                detail=detail,
            )
        )

    check_ids: dict[str, CheckRecord] = {}
    for check in checks:
        normalized_id = check.check_id.casefold()
        if not _identifier_is_valid(check.check_id):
            add_issue(
                check.source,
                check.line,
                check.check_id,
                "invalid_check_id",
                "check ID must be uppercase, hyphenated, and end in digits",
            )
        if normalized_id in check_ids:
            first = check_ids[normalized_id]
            add_issue(
                check.source,
                check.line,
                check.check_id,
                "duplicate_check_id",
                f"first declared at {first.source}:{first.line}",
            )
        else:
            check_ids[normalized_id] = check

        fields = {
            "check or test": check.item,
            "acceptance reference": check.acceptance_reference,
            "owner": check.owner,
            "status": check.status,
        }
        for label, value in fields.items():
            if _is_missing(value, missing):
                add_issue(
                    check.source,
                    check.line,
                    check.check_id,
                    "missing_check_field",
                    f"{label} is required",
                )
        if not check.evidence_ids:
            add_issue(
                check.source,
                check.line,
                check.check_id,
                "missing_evidence_reference",
                "at least one evidence ID is required",
            )
        seen_references: set[str] = set()
        for evidence_id in check.evidence_ids:
            normalized_evidence_id = evidence_id.casefold()
            if not _identifier_is_valid(evidence_id):
                add_issue(
                    check.source,
                    check.line,
                    check.check_id,
                    "invalid_evidence_reference",
                    f"invalid evidence ID: {evidence_id}",
                )
            if normalized_evidence_id in seen_references:
                add_issue(
                    check.source,
                    check.line,
                    check.check_id,
                    "duplicate_evidence_reference",
                    f"evidence ID is repeated in the row: {evidence_id}",
                )
            seen_references.add(normalized_evidence_id)

    evidence_by_id: dict[str, EvidenceRecord] = {}
    for record in evidence:
        normalized_id = record.evidence_id.casefold()
        if not _identifier_is_valid(record.evidence_id):
            add_issue(
                record.source,
                record.line,
                record.evidence_id,
                "invalid_evidence_id",
                "evidence ID must be uppercase, hyphenated, and end in digits",
            )
        if normalized_id in evidence_by_id:
            first = evidence_by_id[normalized_id]
            add_issue(
                record.source,
                record.line,
                record.evidence_id,
                "duplicate_evidence_id",
                f"first declared at {first.source}:{first.line}",
            )
        else:
            evidence_by_id[normalized_id] = record

        fields = {
            "evidence location": record.location,
            "revision": record.revision,
            "approval status": record.approval_status,
        }
        for label, value in fields.items():
            if _is_missing(value, missing):
                add_issue(
                    record.source,
                    record.line,
                    record.evidence_id,
                    "missing_evidence_field",
                    f"{label} is required",
                )

    referenced_ids: set[str] = set()
    for check in checks:
        is_completed = normalize_heading(check.status) in completed
        for evidence_id in _unique_evidence_ids(check.evidence_ids):
            normalized_id = evidence_id.casefold()
            record = evidence_by_id.get(normalized_id)
            if record is None:
                add_issue(
                    check.source,
                    check.line,
                    check.check_id,
                    "unknown_evidence_reference",
                    f"evidence ID is not registered: {evidence_id}",
                )
                continue
            referenced_ids.add(normalized_id)
            if (
                is_completed
                and normalize_heading(record.approval_status) not in accepted
            ):
                add_issue(
                    check.source,
                    check.line,
                    check.check_id,
                    "unaccepted_evidence",
                    f"{evidence_id} has approval status {record.approval_status!r}",
                )

    for normalized_id, record in evidence_by_id.items():
        if normalized_id not in referenced_ids:
            add_issue(
                record.source,
                record.line,
                record.evidence_id,
                "orphan_evidence",
                "evidence record is not referenced by any check",
            )
    return issues


def summarize_traceability(
    checks: Sequence[CheckRecord],
    evidence: Sequence[EvidenceRecord],
    issues: Sequence[TraceabilityIssue],
    completed_statuses: Sequence[str] = DEFAULT_COMPLETED_STATUSES,
) -> dict[str, object]:
    completed = {normalize_heading(value) for value in completed_statuses}
    references: dict[str, list[str]] = defaultdict(list)
    for check in checks:
        for evidence_id in _unique_evidence_ids(check.evidence_ids):
            references[evidence_id.casefold()].append(check.check_id)
    evidence_items = []
    for record in evidence:
        item = asdict(record)
        item["referenced_by"] = references.get(record.evidence_id.casefold(), [])
        evidence_items.append(item)
    return {
        "source_files": sorted({record.source for record in [*checks, *evidence]}),
        "check_count": len(checks),
        "completed_check_count": sum(
            normalize_heading(check.status) in completed for check in checks
        ),
        "evidence_count": len(evidence),
        "referenced_evidence_count": len(references),
        "issue_count": len(issues),
        "checks": [asdict(check) for check in checks],
        "evidence": evidence_items,
        "issues": [asdict(issue) for issue in issues],
    }


def _markdown_cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_markdown(summary: dict[str, object]) -> str:
    lines = [
        GENERATED_MARKER,
        "<!-- markdownlint-disable MD013 -->",
        "",
        "# Commissioning Evidence Traceability Audit",
        "",
        f"Source files: {len(summary['source_files'])}  ",
        f"Checks: {summary['check_count']}  ",
        f"Completed checks: {summary['completed_check_count']}  ",
        f"Evidence records: {summary['evidence_count']}  ",
        f"Issues: {summary['issue_count']}",
    ]
    issues = summary["issues"]
    if issues:
        lines.extend(
            [
                "",
                "## Issues",
                "",
                "| Source | Line | Record | Kind | Detail |",
                "| --- | ---: | --- | --- | --- |",
            ]
        )
        lines.extend(
            "| {source} | {line} | {record_id} | {kind} | {detail} |".format(
                **{key: _markdown_cell(value) for key, value in issue.items()}
            )
            for issue in issues
        )
    lines.extend(
        [
            "",
            "## Check Coverage",
            "",
            "| Check ID | Check or Test | Status | Evidence IDs |",
            "| --- | --- | --- | --- |",
        ]
    )
    lines.extend(
        "| {check_id} | {item} | {status} | {evidence_ids} |".format(
            check_id=_markdown_cell(check["check_id"]),
            item=_markdown_cell(check["item"]),
            status=_markdown_cell(check["status"]),
            evidence_ids=_markdown_cell(", ".join(check["evidence_ids"])),
        )
        for check in summary["checks"]
    )
    lines.extend(
        [
            "",
            "## Evidence Register",
            "",
            "| Evidence ID | Approval Status | Revision | Referenced By | Location |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    lines.extend(
        "| {evidence_id} | {approval_status} | {revision} | {referenced_by} | {location} |".format(
            evidence_id=_markdown_cell(record["evidence_id"]),
            approval_status=_markdown_cell(record["approval_status"]),
            revision=_markdown_cell(record["revision"]),
            referenced_by=_markdown_cell(", ".join(record["referenced_by"])),
            location=_markdown_cell(record["location"]),
        )
        for record in summary["evidence"]
    )
    return "\n".join(lines) + "\n"


def _option_values(
    values: Sequence[str] | None,
    defaults: Sequence[str],
    context: str,
) -> tuple[str, ...]:
    selected = tuple(
        defaults if values is None else (value.strip() for value in values)
    )
    if not selected or any(not value for value in selected):
        raise ValueError(f"{context} must contain nonempty values")
    normalized = [normalize_heading(value) for value in selected]
    if len(normalized) != len(set(normalized)):
        raise ValueError(f"{context} contains case-insensitive duplicates")
    return selected


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Audit commissioning checks against a controlled evidence register."
    )
    parser.add_argument("paths", nargs="*", type=Path)
    parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    parser.add_argument("--output", type=Path)
    parser.add_argument(
        "--completed-status",
        action="append",
        help="status that requires accepted evidence; repeat to replace defaults",
    )
    parser.add_argument(
        "--accepted-evidence-status",
        action="append",
        help="accepted evidence state; repeat to replace defaults",
    )
    parser.add_argument(
        "--missing-value",
        action="append",
        help="controlled placeholder treated as missing; repeat to replace defaults",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        completed_statuses = _option_values(
            args.completed_status,
            DEFAULT_COMPLETED_STATUSES,
            "completed statuses",
        )
        accepted_statuses = _option_values(
            args.accepted_evidence_status,
            DEFAULT_ACCEPTED_EVIDENCE_STATUSES,
            "accepted evidence statuses",
        )
        missing_values = _option_values(
            args.missing_value,
            DEFAULT_MISSING_VALUES,
            "missing values",
        )
        inputs = args.paths or [Path("templates/commissioning-evidence-matrix.md")]
        paths = expand_paths(inputs)
        checks: list[CheckRecord] = []
        evidence: list[EvidenceRecord] = []
        for path in paths:
            path_checks, path_evidence = extract_traceability_records(path)
            checks.extend(path_checks)
            evidence.extend(path_evidence)
        if not checks:
            raise ValueError("no commissioning check rows found")
        if not evidence:
            raise ValueError("no evidence register rows found")
        issues = audit_traceability(
            checks,
            evidence,
            completed_statuses=completed_statuses,
            accepted_evidence_statuses=accepted_statuses,
            missing_values=missing_values,
        )
    except (OSError, ValueError) as error:
        print(f"Evidence traceability audit failed: {error}", file=sys.stderr)
        return 1

    summary = summarize_traceability(
        checks,
        evidence,
        issues,
        completed_statuses,
    )
    rendered = (
        json.dumps(summary, indent=2) + "\n"
        if args.format == "json"
        else render_markdown(summary)
    )
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    else:
        print(rendered, end="")

    for issue in issues:
        print(
            f"{issue.source}:{issue.line}: {issue.record_id}: "
            f"{issue.kind}: {issue.detail}",
            file=sys.stderr,
        )
    if issues:
        print(
            f"Evidence traceability gate failed with {len(issues)} issue(s).",
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
