from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Sequence

try:
    from scripts.summarize_status import (
        expand_paths,
        is_status_legend,
        normalize_heading,
    )
    from scripts.validate_templates import table_blocks, table_cells
except ModuleNotFoundError:
    from summarize_status import expand_paths, is_status_legend, normalize_heading
    from validate_templates import table_blocks, table_cells


GENERATED_MARKER = "<!-- generated by scripts/audit_completeness.py -->"


@dataclass(frozen=True)
class RequiredField:
    label: str
    columns: tuple[str, ...]


@dataclass(frozen=True)
class CompletenessRule:
    name: str
    match_columns: tuple[str, ...]
    match_values: tuple[str, ...]
    required_fields: tuple[RequiredField, ...]


@dataclass(frozen=True)
class CompletenessPolicy:
    missing_values: tuple[str, ...]
    rules: tuple[CompletenessRule, ...]


@dataclass(frozen=True)
class RuleMatch:
    source: str
    line: int
    item: str
    rule: str
    match_column: str
    match_value: str


@dataclass(frozen=True)
class CompletenessViolation:
    source: str
    line: int
    item: str
    rule: str
    match_column: str
    match_value: str
    field: str
    columns: tuple[str, ...]
    values: tuple[str, ...]
    reason: str


def _string_tuple(
    value: object,
    context: str,
    *,
    require_values: bool = True,
) -> tuple[str, ...]:
    if not isinstance(value, list) or any(
        not isinstance(item, str) or not item.strip() for item in value
    ):
        raise ValueError(f"{context} must be a list of nonempty strings")
    values = tuple(item.strip() for item in value)
    if require_values and not values:
        raise ValueError(f"{context} must not be empty")
    normalized = [normalize_heading(item) for item in values]
    if len(normalized) != len(set(normalized)):
        raise ValueError(f"{context} contains case-insensitive duplicates")
    return values


def load_completeness_policy(path: Path) -> CompletenessPolicy:
    """Load and strictly validate conditional field-completeness rules."""

    document = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        raise ValueError("completeness policy root must be a JSON object")
    unknown_root_fields = sorted(set(document) - {"missing_values", "rules"})
    if unknown_root_fields:
        raise ValueError(
            "completeness policy has unknown fields: " + ", ".join(unknown_root_fields)
        )

    missing_values = _string_tuple(
        document.get("missing_values", []),
        "policy missing_values",
        require_values=False,
    )
    raw_rules = document.get("rules")
    if not isinstance(raw_rules, list) or not raw_rules:
        raise ValueError("policy rules must be a nonempty list")

    rules: list[CompletenessRule] = []
    normalized_rule_names: set[str] = set()
    for rule_index, raw_rule in enumerate(raw_rules, start=1):
        context = f"policy rule {rule_index}"
        if not isinstance(raw_rule, dict):
            raise ValueError(f"{context} must be a JSON object")
        unknown_rule_fields = sorted(
            set(raw_rule) - {"name", "match", "required_fields"}
        )
        if unknown_rule_fields:
            raise ValueError(
                f"{context} has unknown fields: " + ", ".join(unknown_rule_fields)
            )

        name = raw_rule.get("name")
        if not isinstance(name, str) or not name.strip():
            raise ValueError(f"{context} name must be a nonempty string")
        name = name.strip()
        normalized_name = normalize_heading(name)
        if normalized_name in normalized_rule_names:
            raise ValueError("policy rules contain case-insensitive duplicate names")
        normalized_rule_names.add(normalized_name)

        raw_match = raw_rule.get("match")
        if not isinstance(raw_match, dict):
            raise ValueError(f"{context} match must be a JSON object")
        unknown_match_fields = sorted(set(raw_match) - {"columns", "values"})
        if unknown_match_fields:
            raise ValueError(
                f"{context} match has unknown fields: "
                + ", ".join(unknown_match_fields)
            )
        match_columns = _string_tuple(
            raw_match.get("columns"),
            f"{context} match columns",
        )
        match_values = _string_tuple(
            raw_match.get("values"),
            f"{context} match values",
        )

        raw_fields = raw_rule.get("required_fields")
        if not isinstance(raw_fields, list) or not raw_fields:
            raise ValueError(f"{context} required_fields must be a nonempty list")
        required_fields: list[RequiredField] = []
        normalized_labels: set[str] = set()
        column_owners: dict[str, str] = {}
        for field_index, raw_field in enumerate(raw_fields, start=1):
            field_context = f"{context} required field {field_index}"
            if not isinstance(raw_field, dict):
                raise ValueError(f"{field_context} must be a JSON object")
            unknown_field_keys = sorted(set(raw_field) - {"label", "columns"})
            if unknown_field_keys:
                raise ValueError(
                    f"{field_context} has unknown fields: "
                    + ", ".join(unknown_field_keys)
                )
            label = raw_field.get("label")
            if not isinstance(label, str) or not label.strip():
                raise ValueError(f"{field_context} label must be a nonempty string")
            label = label.strip()
            normalized_label = normalize_heading(label)
            if normalized_label in normalized_labels:
                raise ValueError(f"{context} has duplicate required field labels")
            normalized_labels.add(normalized_label)
            columns = _string_tuple(
                raw_field.get("columns"),
                f"{field_context} columns",
            )
            for column in columns:
                normalized_column = normalize_heading(column)
                if normalized_column in column_owners:
                    raise ValueError(
                        f"{context} assigns column {column!r} to both "
                        f"{column_owners[normalized_column]!r} and {label!r}"
                    )
                column_owners[normalized_column] = label
            required_fields.append(RequiredField(label=label, columns=columns))

        rules.append(
            CompletenessRule(
                name=name,
                match_columns=match_columns,
                match_values=match_values,
                required_fields=tuple(required_fields),
            )
        )

    return CompletenessPolicy(
        missing_values=missing_values,
        rules=tuple(rules),
    )


def _is_generated_report(lines: list[str]) -> bool:
    return bool(
        lines
        and lines[0].strip().startswith("<!-- generated by scripts/")
        and lines[0].strip().endswith(" -->")
    )


def _is_missing(value: str, missing_values: set[str]) -> bool:
    return not value.strip() or normalize_heading(value) in missing_values


def extract_completeness_results(
    path: Path,
    policy: CompletenessPolicy,
) -> tuple[list[RuleMatch], list[CompletenessViolation]]:
    """Evaluate conditional required fields in every Markdown table row."""

    lines = path.read_text(encoding="utf-8").splitlines()
    if _is_generated_report(lines):
        return [], []

    normalized_missing_values = {
        normalize_heading(value) for value in policy.missing_values
    }
    matches: list[RuleMatch] = []
    violations: list[CompletenessViolation] = []
    for start_line, block in table_blocks(lines):
        if len(block) < 3:
            continue
        header = table_cells(block[0])
        if is_status_legend(header):
            continue
        normalized_header = [normalize_heading(column) for column in header]
        rows: list[tuple[int, list[str]]] = []
        for offset, row in enumerate(block[2:], start=2):
            row_line = start_line + offset
            cells = table_cells(row)
            if len(cells) != len(header):
                raise ValueError(
                    f"{path}:{row_line}: table row has {len(cells)} cells; "
                    f"expected {len(header)}"
                )
            if any(cell for cell in cells):
                rows.append((row_line, cells))

        for rule in policy.rules:
            match_aliases = {normalize_heading(column) for column in rule.match_columns}
            match_indices = [
                index
                for index, column in enumerate(normalized_header)
                if column in match_aliases
            ]
            if len(match_indices) > 1:
                matched_columns = ", ".join(header[index] for index in match_indices)
                raise ValueError(
                    f"{path}:{start_line}: rule {rule.name!r} matched multiple "
                    f"columns: {matched_columns}"
                )
            if not match_indices:
                continue
            match_index = match_indices[0]
            accepted_values = {normalize_heading(value) for value in rule.match_values}

            field_indices: list[tuple[RequiredField, list[int]]] = []
            for field in rule.required_fields:
                aliases = {normalize_heading(column) for column in field.columns}
                indices = [
                    index
                    for index, column in enumerate(normalized_header)
                    if column in aliases
                ]
                field_indices.append((field, indices))

            for row_line, cells in rows:
                match_value = cells[match_index]
                if normalize_heading(match_value) not in accepted_values:
                    continue
                item = next(
                    (
                        cell
                        for index, cell in enumerate(cells)
                        if index != match_index and cell
                    ),
                    f"Row {row_line}",
                )
                base = {
                    "source": path.as_posix(),
                    "line": row_line,
                    "item": item,
                    "rule": rule.name,
                    "match_column": header[match_index],
                    "match_value": match_value,
                }
                matches.append(RuleMatch(**base))

                for field, indices in field_indices:
                    if not indices:
                        violations.append(
                            CompletenessViolation(
                                **base,
                                field=field.label,
                                columns=field.columns,
                                values=(),
                                reason="required field column is absent from table",
                            )
                        )
                        continue
                    values = tuple(cells[index] for index in indices)
                    if all(
                        _is_missing(value, normalized_missing_values)
                        for value in values
                    ):
                        violations.append(
                            CompletenessViolation(
                                **base,
                                field=field.label,
                                columns=tuple(header[index] for index in indices),
                                values=values,
                                reason="required field value is missing",
                            )
                        )
    return matches, violations


def summarize_completeness(
    matches: Sequence[RuleMatch],
    violations: Sequence[CompletenessViolation],
    policy: CompletenessPolicy,
    policy_source: str,
) -> dict[str, object]:
    match_counts = Counter(record.rule for record in matches)
    violation_counts = Counter(record.rule for record in violations)
    return {
        "policy_source": policy_source,
        "source_files": sorted({record.source for record in matches}),
        "evaluated_row_count": len(matches),
        "violation_count": len(violations),
        "rule_counts": [
            {
                "rule": rule.name,
                "evaluated_rows": match_counts[rule.name],
                "violations": violation_counts[rule.name],
            }
            for rule in policy.rules
        ],
        "violations": [asdict(violation) for violation in violations],
    }


def _markdown_cell(value: object) -> str:
    if isinstance(value, (list, tuple)):
        value = ", ".join(str(item) if item else "(blank)" for item in value)
    if value is None or value == "":
        value = "-"
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_markdown(summary: dict[str, object]) -> str:
    lines = [
        GENERATED_MARKER,
        "<!-- markdownlint-disable MD013 -->",
        "",
        "# Readiness Conditional Completeness Audit",
        "",
        f"Policy source: {_markdown_cell(summary['policy_source'])}  ",
        f"Source files: {len(summary['source_files'])}  ",
        f"Evaluated rows: {summary['evaluated_row_count']}  ",
        f"Violations: {summary['violation_count']}",
        "",
        "## Rule Counts",
        "",
        "| Rule | Evaluated Rows | Violations |",
        "| --- | ---: | ---: |",
    ]
    lines.extend(
        f"| {_markdown_cell(item['rule'])} | {item['evaluated_rows']} | "
        f"{item['violations']} |"
        for item in summary["rule_counts"]
    )
    lines.extend(["", "## Violations", ""])
    violations = summary["violations"]
    if not violations:
        lines.append("No completeness violations found.")
        return "\n".join(lines) + "\n"

    lines.extend(
        [
            "| Source | Line | Item | Rule | Match | Field | Columns | Values | Reason |",
            "| --- | ---: | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for violation in violations:
        lines.append(
            "| {source} | {line} | {item} | {rule} | {match} | {field} | "
            "{columns} | {values} | {reason} |".format(
                source=_markdown_cell(violation["source"]),
                line=violation["line"],
                item=_markdown_cell(violation["item"]),
                rule=_markdown_cell(violation["rule"]),
                match=_markdown_cell(
                    f"{violation['match_column']}={violation['match_value']}"
                ),
                field=_markdown_cell(violation["field"]),
                columns=_markdown_cell(violation["columns"]),
                values=_markdown_cell(violation["values"]),
                reason=_markdown_cell(violation["reason"]),
            )
        )
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Audit conditional owner, deadline, approval, revision, and evidence "
            "fields in Markdown tables."
        )
    )
    parser.add_argument("paths", nargs="*", type=Path)
    parser.add_argument("--policy", type=Path, required=True)
    parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    parser.add_argument("--output", type=Path)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        policy = load_completeness_policy(args.policy)
        paths = expand_paths(args.paths or [Path("templates")])
        matches: list[RuleMatch] = []
        violations: list[CompletenessViolation] = []
        for path in paths:
            path_matches, path_violations = extract_completeness_results(path, policy)
            matches.extend(path_matches)
            violations.extend(path_violations)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"Completeness audit failed: {error}", file=sys.stderr)
        return 1

    if not matches:
        print(
            "Completeness audit failed: no rows matched any policy rule.",
            file=sys.stderr,
        )
        return 1

    summary = summarize_completeness(
        matches,
        violations,
        policy,
        args.policy.as_posix(),
    )
    rendered = (
        json.dumps(summary, indent=2) + "\n"
        if args.format == "json"
        else render_markdown(summary)
    )
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    else:
        print(rendered, end="")

    if violations:
        print(
            f"Completeness audit gate failed with {len(violations)} violation(s).",
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
