from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path
from typing import Sequence

try:
    from scripts.summarize_status import expand_paths, normalize_heading
    from scripts.validate_templates import table_blocks, table_cells
except ModuleNotFoundError:
    from summarize_status import expand_paths, normalize_heading
    from validate_templates import table_blocks, table_cells


GENERATED_MARKER = "<!-- generated by scripts/audit_punch_list.py -->"
IDENTIFIER_PATTERN = re.compile(r"^[A-Z][A-Z0-9]*(?:-[A-Z0-9]+)*-\d+$")
SEVERITIES = ("Critical", "Major", "Minor")
STATUSES = (
    "Open",
    "In progress",
    "Ready for verification",
    "Closed",
    "Deferred",
)
TERMINAL_STATUSES = ("Closed", "Deferred")
EVIDENCE_REQUIRED_STATUSES = ("Ready for verification", "Closed", "Deferred")
MISSING_VALUES = ("TBD", "TBC", "N/A", "NA", "-")

COLUMNS = {
    "item_id": ("ID", "Item ID", "Finding ID", "Nonconformance ID"),
    "severity": ("Severity",),
    "finding": ("Finding or Nonconformance", "Finding", "Nonconformance"),
    "system_area": ("System Area", "Area", "Subsystem"),
    "owner": ("Owner", "Responsible Owner"),
    "evidence_link": ("Evidence Link", "Evidence", "Evidence Location"),
    "target_close_date": ("Target Close Date", "Due Date"),
    "status": ("Status",),
    "closeout_note": (
        "Verification / Closeout Note",
        "Verification or Closeout Note",
        "Closeout Note",
    ),
}


@dataclass(frozen=True)
class PunchListRecord:
    source: str
    line: int
    item_id: str
    severity: str
    finding: str
    system_area: str
    owner: str
    evidence_link: str
    target_close_date: str
    status: str
    closeout_note: str


@dataclass(frozen=True)
class PunchListIssue:
    source: str
    line: int
    item_id: str
    kind: str
    detail: str


def _normalized_aliases(aliases: Sequence[str]) -> set[str]:
    return {normalize_heading(alias) for alias in aliases}


def _column_indices(header: Sequence[str], context: str) -> dict[str, int]:
    normalized_header = [normalize_heading(value) for value in header]
    indices: dict[str, int] = {}
    for field, aliases in COLUMNS.items():
        matches = [
            index
            for index, column in enumerate(normalized_header)
            if column in _normalized_aliases(aliases)
        ]
        if not matches:
            raise ValueError(
                f"{context}: missing required column for {field}: "
                + ", ".join(aliases)
            )
        if len(matches) > 1:
            columns = ", ".join(header[index] for index in matches)
            raise ValueError(f"{context}: ambiguous {field} columns: {columns}")
        indices[field] = matches[0]
    return indices


def _is_punch_list_header(header: Sequence[str]) -> bool:
    normalized = {normalize_heading(value) for value in header}
    return bool(
        normalized & _normalized_aliases(COLUMNS["item_id"])
        and normalized & _normalized_aliases(COLUMNS["finding"])
    )


def extract_punch_list_records(path: Path) -> list[PunchListRecord]:
    """Extract punch-list rows from the matching Markdown table."""

    lines = path.read_text(encoding="utf-8").splitlines()
    if lines and lines[0].strip() == GENERATED_MARKER:
        return []

    records: list[PunchListRecord] = []
    for start_line, block in table_blocks(lines):
        if len(block) < 3:
            continue
        header = table_cells(block[0])
        if not _is_punch_list_header(header):
            continue
        indices = _column_indices(header, f"{path}:{start_line}")
        for offset, row in enumerate(block[2:], start=2):
            cells = table_cells(row)
            row_line = start_line + offset
            if len(cells) != len(header):
                raise ValueError(
                    f"{path}:{row_line}: table row has {len(cells)} cells; "
                    f"expected {len(header)}"
                )
            if not any(cells):
                continue
            values = {field: cells[index] for field, index in indices.items()}
            records.append(
                PunchListRecord(
                    source=path.as_posix(),
                    line=row_line,
                    **values,
                )
            )
    return records


def _is_missing(value: str) -> bool:
    return not value.strip() or normalize_heading(value) in {
        normalize_heading(item) for item in MISSING_VALUES
    }


def _parse_date(value: str) -> date | None:
    try:
        parsed = date.fromisoformat(value)
    except ValueError:
        return None
    return parsed if parsed.isoformat() == value else None


def audit_punch_list(
    records: Sequence[PunchListRecord],
    as_of: date,
) -> list[PunchListIssue]:
    """Return deterministic punch-list governance and closeout issues."""

    issues: list[PunchListIssue] = []
    seen_ids: dict[str, PunchListRecord] = {}
    accepted_severities = {normalize_heading(value) for value in SEVERITIES}
    accepted_statuses = {normalize_heading(value) for value in STATUSES}
    terminal_statuses = {normalize_heading(value) for value in TERMINAL_STATUSES}
    evidence_statuses = {
        normalize_heading(value) for value in EVIDENCE_REQUIRED_STATUSES
    }

    def add(record: PunchListRecord, kind: str, detail: str) -> None:
        issues.append(
            PunchListIssue(
                source=record.source,
                line=record.line,
                item_id=record.item_id or f"Row {record.line}",
                kind=kind,
                detail=detail,
            )
        )

    for record in records:
        required = {
            "ID": record.item_id,
            "Severity": record.severity,
            "Finding": record.finding,
            "System Area": record.system_area,
            "Owner": record.owner,
            "Target Close Date": record.target_close_date,
            "Status": record.status,
        }
        missing_fields = [name for name, value in required.items() if _is_missing(value)]
        if missing_fields:
            add(
                record,
                "missing_required_field",
                "missing controlled value for " + ", ".join(missing_fields),
            )

        if record.item_id and not IDENTIFIER_PATTERN.fullmatch(record.item_id):
            add(
                record,
                "invalid_item_id",
                "ID must use an uppercase project prefix and numeric suffix",
            )
        normalized_id = record.item_id.casefold()
        if record.item_id and normalized_id in seen_ids:
            first = seen_ids[normalized_id]
            add(
                record,
                "duplicate_item_id",
                f"duplicates {first.source}:{first.line}",
            )
        elif record.item_id:
            seen_ids[normalized_id] = record

        normalized_severity = normalize_heading(record.severity)
        normalized_status = normalize_heading(record.status)
        if (
            not _is_missing(record.severity)
            and normalized_severity not in accepted_severities
        ):
            add(
                record,
                "invalid_severity",
                "severity must be Critical, Major, or Minor",
            )
        if (
            not _is_missing(record.status)
            and normalized_status not in accepted_statuses
        ):
            add(
                record,
                "invalid_status",
                "status must use the tracker vocabulary",
            )

        target_date = None
        if not _is_missing(record.target_close_date):
            target_date = _parse_date(record.target_close_date)
            if target_date is None:
                add(
                    record,
                    "invalid_target_close_date",
                    "Target Close Date must use YYYY-MM-DD",
                )
        is_terminal = normalized_status in terminal_statuses
        if target_date is not None and not is_terminal and target_date < as_of:
            add(
                record,
                "overdue_item",
                f"active item is {(as_of - target_date).days} day(s) overdue",
            )
        if normalized_severity == "critical" and not is_terminal:
            add(
                record,
                "unresolved_critical_item",
                "critical item remains active",
            )
        if normalized_severity == "critical" and normalized_status == "deferred":
            add(
                record,
                "critical_item_deferred",
                "critical items cannot pass this gate as Deferred",
            )
        if normalized_status in evidence_statuses and _is_missing(record.evidence_link):
            add(
                record,
                "missing_closeout_evidence",
                f"{record.status} requires an Evidence Link",
            )
        if is_terminal and _is_missing(record.closeout_note):
            add(
                record,
                "missing_closeout_note",
                f"{record.status} requires a verification or closeout note",
            )

    return issues


def summarize_punch_list(
    records: Sequence[PunchListRecord],
    issues: Sequence[PunchListIssue],
    as_of: date,
) -> dict[str, object]:
    status_counts = Counter(normalize_heading(record.status) for record in records)
    severity_counts = Counter(
        normalize_heading(record.severity) for record in records
    )
    items: list[dict[str, object]] = []
    terminal = {normalize_heading(value) for value in TERMINAL_STATUSES}
    for record in records:
        parsed_date = _parse_date(record.target_close_date)
        days_to_target = (parsed_date - as_of).days if parsed_date else None
        item = asdict(record)
        item.update(
            {
                "days_to_target": days_to_target,
                "overdue": (
                    days_to_target is not None
                    and days_to_target < 0
                    and normalize_heading(record.status) not in terminal
                ),
            }
        )
        items.append(item)
    return {
        "as_of": as_of.isoformat(),
        "source_files": sorted({record.source for record in records}),
        "item_count": len(records),
        "status_counts": {
            status: status_counts[normalize_heading(status)] for status in STATUSES
        },
        "severity_counts": {
            severity: severity_counts[normalize_heading(severity)]
            for severity in SEVERITIES
        },
        "issue_count": len(issues),
        "issues": [asdict(issue) for issue in issues],
        "items": items,
    }


def _markdown_cell(value: object) -> str:
    if value is None or value == "":
        return "-"
    if isinstance(value, bool):
        return str(value).lower()
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_markdown(summary: dict[str, object]) -> str:
    lines = [
        GENERATED_MARKER,
        "<!-- markdownlint-disable MD013 -->",
        "",
        "# Punch-List Closeout Audit",
        "",
        f"As of: {summary['as_of']}  ",
        f"Source files: {len(summary['source_files'])}  ",
        f"Items: {summary['item_count']}  ",
        f"Issues: {summary['issue_count']}",
        "",
        "## Counts",
        "",
        "| Dimension | Value | Count |",
        "| --- | --- | ---: |",
    ]
    lines.extend(
        f"| Severity | {severity} | {summary['severity_counts'][severity]} |"
        for severity in SEVERITIES
    )
    lines.extend(
        f"| Status | {status} | {summary['status_counts'][status]} |"
        for status in STATUSES
    )
    if summary["issues"]:
        lines.extend(
            [
                "",
                "## Issues",
                "",
                "| Source | Line | ID | Kind | Detail |",
                "| --- | ---: | --- | --- | --- |",
            ]
        )
        for issue in summary["issues"]:
            lines.append(
                "| {source} | {line} | {item_id} | {kind} | {detail} |".format(
                    **{key: _markdown_cell(value) for key, value in issue.items()}
                )
            )
    lines.extend(
        [
            "",
            "## Items",
            "",
            "| ID | Severity | System Area | Owner | Target | Days | Status | "
            "Overdue | Evidence |",
            "| --- | --- | --- | --- | --- | ---: | --- | --- | --- |",
        ]
    )
    for item in summary["items"]:
        lines.append(
            "| {item_id} | {severity} | {system_area} | {owner} | "
            "{target_close_date} | {days_to_target} | {status} | {overdue} | "
            "{evidence_link} |".format(
                **{key: _markdown_cell(value) for key, value in item.items()}
            )
        )
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Audit BESS punch-list governance and closeout evidence."
    )
    parser.add_argument("paths", nargs="*", type=Path)
    parser.add_argument("--as-of", required=True, metavar="YYYY-MM-DD")
    parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    parser.add_argument("--output", type=Path)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        as_of = _parse_date(args.as_of)
        if as_of is None:
            raise ValueError("--as-of must use YYYY-MM-DD")
        inputs = args.paths or [Path("examples/punch-list-closeout-passing.md")]
        paths = expand_paths(inputs)
        records = [
            record
            for path in paths
            for record in extract_punch_list_records(path)
        ]
        if not records:
            raise ValueError("no punch-list rows found")
        issues = audit_punch_list(records, as_of)
    except (OSError, ValueError) as error:
        print(f"Punch-list audit failed: {error}", file=sys.stderr)
        return 1

    summary = summarize_punch_list(records, issues, as_of)
    rendered = (
        json.dumps(summary, indent=2) + "\n"
        if args.format == "json"
        else render_markdown(summary)
    )
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    else:
        print(rendered, end="")

    for issue in issues:
        print(
            f"{issue.source}:{issue.line}: {issue.item_id}: "
            f"{issue.kind}: {issue.detail}",
            file=sys.stderr,
        )
    if issues:
        print(
            f"Punch-list gate failed with {len(issues)} issue(s).",
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
