from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict
from datetime import date
from pathlib import Path
from typing import Sequence

try:
    from scripts.audit_completeness import (
        CompletenessPolicy,
        extract_completeness_results,
        load_completeness_policy,
        summarize_completeness,
    )
    from scripts.audit_deadlines import (
        DEADLINE_STATES,
        DEFAULT_DATE_COLUMNS,
        DEFAULT_MISSING_DATE_VALUES,
        DEFAULT_TERMINAL_STATUSES,
        extract_deadline_records,
        normalized_values,
        parse_iso_date,
        summarize_deadlines,
    )
    from scripts.summarize_status import (
        StatusPolicy,
        evaluate_status_policy,
        expand_paths,
        extract_status_records,
        load_status_policy,
        summarize_records,
    )
except ModuleNotFoundError:
    from audit_completeness import (
        CompletenessPolicy,
        extract_completeness_results,
        load_completeness_policy,
        summarize_completeness,
    )
    from audit_deadlines import (
        DEADLINE_STATES,
        DEFAULT_DATE_COLUMNS,
        DEFAULT_MISSING_DATE_VALUES,
        DEFAULT_TERMINAL_STATUSES,
        extract_deadline_records,
        normalized_values,
        parse_iso_date,
        summarize_deadlines,
    )
    from summarize_status import (
        StatusPolicy,
        evaluate_status_policy,
        expand_paths,
        extract_status_records,
        load_status_policy,
        summarize_records,
    )


GENERATED_MARKER = "<!-- generated by scripts/audit_readiness.py -->"
DEFAULT_DEADLINE_FAIL_STATES = ("overdue", "missing")


def _deadline_fail_states(values: Sequence[str]) -> tuple[str, ...]:
    normalized = tuple(value.casefold().strip() for value in values)
    unknown = sorted(set(normalized) - set(DEADLINE_STATES))
    if unknown:
        raise ValueError("unknown deadline failure states: " + ", ".join(unknown))
    if len(normalized) != len(set(normalized)):
        raise ValueError("deadline failure states contain duplicates")
    return tuple(state for state in DEADLINE_STATES if state in normalized)


def evaluate_readiness(
    paths: Sequence[Path],
    *,
    status_policy: StatusPolicy,
    status_policy_source: str,
    completeness_policy: CompletenessPolicy,
    completeness_policy_source: str,
    as_of: date,
    deadline_fail_states: Sequence[str] = DEFAULT_DEADLINE_FAIL_STATES,
    date_columns: Sequence[str] = DEFAULT_DATE_COLUMNS,
    terminal_statuses: Sequence[str] = DEFAULT_TERMINAL_STATUSES,
    missing_date_values: Sequence[str] = DEFAULT_MISSING_DATE_VALUES,
) -> dict[str, object]:
    """Evaluate all readiness controls and return one release-gate report."""

    normalized_values(date_columns, "date columns")
    normalized_values(terminal_statuses, "terminal statuses")
    normalized_values(missing_date_values, "missing date values")
    selected_deadline_states = _deadline_fail_states(deadline_fail_states)

    status_records = [
        record for path in paths for record in extract_status_records(path)
    ]
    if not status_records:
        raise ValueError("no status-bearing rows found")
    status_violations = evaluate_status_policy(status_records, status_policy)
    status_summary = summarize_records(status_records)
    status_summary.update(
        {
            "result": "fail" if status_violations else "pass",
            "policy_source": status_policy_source,
            "finding_count": len(status_violations),
            "violations": [asdict(violation) for violation in status_violations],
        }
    )

    deadline_records = [
        record
        for path in paths
        for record in extract_deadline_records(
            path,
            as_of,
            date_columns,
            terminal_statuses,
            missing_date_values,
        )
    ]
    if not deadline_records:
        raise ValueError("no deadline-bearing rows found")
    deadline_failures = [
        record
        for record in deadline_records
        if record.state in selected_deadline_states
    ]
    deadline_summary = summarize_deadlines(deadline_records, as_of)
    deadline_summary.update(
        {
            "result": "fail" if deadline_failures else "pass",
            "fail_states": list(selected_deadline_states),
            "finding_count": len(deadline_failures),
            "failures": [asdict(record) for record in deadline_failures],
        }
    )

    completeness_matches = []
    completeness_violations = []
    for path in paths:
        path_matches, path_violations = extract_completeness_results(
            path,
            completeness_policy,
        )
        completeness_matches.extend(path_matches)
        completeness_violations.extend(path_violations)
    if not completeness_matches:
        raise ValueError("no rows matched any completeness policy rule")
    completeness_summary = summarize_completeness(
        completeness_matches,
        completeness_violations,
        completeness_policy,
        completeness_policy_source,
    )
    completeness_summary.update(
        {
            "result": "fail" if completeness_violations else "pass",
            "finding_count": len(completeness_violations),
        }
    )

    checks = {
        "status_policy": status_summary,
        "deadlines": deadline_summary,
        "conditional_completeness": completeness_summary,
    }
    failed_checks = [
        name for name, summary in checks.items() if summary["result"] == "fail"
    ]
    source_files = sorted(
        {source for summary in checks.values() for source in summary["source_files"]}
    )
    return {
        "gate": {
            "result": "fail" if failed_checks else "pass",
            "finding_count": sum(
                int(summary["finding_count"]) for summary in checks.values()
            ),
            "failed_checks": failed_checks,
        },
        "configuration": {
            "as_of": as_of.isoformat(),
            "status_policy_source": status_policy_source,
            "completeness_policy_source": completeness_policy_source,
            "deadline_fail_states": list(selected_deadline_states),
            "date_columns": list(date_columns),
            "terminal_statuses": list(terminal_statuses),
            "missing_date_values": list(missing_date_values),
        },
        "source_files": source_files,
        "checks": checks,
    }


def _markdown_cell(value: object) -> str:
    if value is None or value == "":
        value = "-"
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_markdown(report: dict[str, object]) -> str:
    gate = report["gate"]
    configuration = report["configuration"]
    checks = report["checks"]
    status_summary = checks["status_policy"]
    deadline_summary = checks["deadlines"]
    completeness_summary = checks["conditional_completeness"]
    lines = [
        GENERATED_MARKER,
        "<!-- markdownlint-disable MD013 -->",
        "",
        "# BESS Readiness Gate",
        "",
        f"Gate result: **{str(gate['result']).upper()}**  ",
        f"As of: {configuration['as_of']}  ",
        f"Source files: {len(report['source_files'])}  ",
        f"Findings: {gate['finding_count']}",
        "",
        "## Check Summary",
        "",
        "| Check | Result | Evaluated rows | Findings |",
        "| --- | --- | ---: | ---: |",
        f"| Status policy | {str(status_summary['result']).upper()} | "
        f"{status_summary['row_count']} | {status_summary['finding_count']} |",
        f"| Deadlines | {str(deadline_summary['result']).upper()} | "
        f"{deadline_summary['row_count']} | {deadline_summary['finding_count']} |",
        f"| Conditional completeness | "
        f"{str(completeness_summary['result']).upper()} | "
        f"{completeness_summary['evaluated_row_count']} | "
        f"{completeness_summary['finding_count']} |",
        "",
        "## Status Policy",
        "",
        f"Policy source: {_markdown_cell(status_summary['policy_source'])}",
        "",
        "| Workflow state | Count |",
        "| --- | ---: |",
    ]
    lines.extend(
        f"| {_markdown_cell(state)} | {count} |"
        for state, count in status_summary["status_counts"].items()
    )
    lines.extend(["", "### Status Findings", ""])
    if not status_summary["violations"]:
        lines.append("No status policy findings.")
    else:
        lines.extend(
            [
                "| Source | Line | Item | Workflow state | Source column | Reason |",
                "| --- | ---: | --- | --- | --- | --- |",
            ]
        )
        lines.extend(
            "| {source} | {line} | {item} | {status} | {column} | {reason} |".format(
                **{key: _markdown_cell(value) for key, value in violation.items()}
            )
            for violation in status_summary["violations"]
        )

    lines.extend(
        [
            "",
            "## Deadlines",
            "",
            "Failure states: " + ", ".join(deadline_summary["fail_states"]) + "  ",
            "",
            "| Deadline state | Count |",
            "| --- | ---: |",
        ]
    )
    lines.extend(
        f"| {state} | {deadline_summary['state_counts'][state]} |"
        for state in DEADLINE_STATES
    )
    lines.extend(["", "### Deadline Findings", ""])
    if not deadline_summary["failures"]:
        lines.append("No deadline findings in the configured failure states.")
    else:
        lines.extend(
            [
                "| Source | Line | Item | Workflow state | Deadline | "
                "Deadline state | Days |",
                "| --- | ---: | --- | --- | --- | --- | ---: |",
            ]
        )
        lines.extend(
            "| {source} | {line} | {item} | {status} | {deadline} | "
            "{state} | {days_to_deadline} |".format(
                **{key: _markdown_cell(value) for key, value in failure.items()}
            )
            for failure in deadline_summary["failures"]
        )

    lines.extend(
        [
            "",
            "## Conditional Completeness",
            "",
            f"Policy source: {_markdown_cell(completeness_summary['policy_source'])}",
            "",
            "| Rule | Evaluated rows | Findings |",
            "| --- | ---: | ---: |",
        ]
    )
    lines.extend(
        f"| {_markdown_cell(rule['rule'])} | {rule['evaluated_rows']} | "
        f"{rule['violations']} |"
        for rule in completeness_summary["rule_counts"]
    )
    lines.extend(["", "### Completeness Findings", ""])
    if not completeness_summary["violations"]:
        lines.append("No conditional completeness findings.")
    else:
        lines.extend(
            [
                "| Source | Line | Item | Rule | Matched value | Field | Reason |",
                "| --- | ---: | --- | --- | --- | --- | --- |",
            ]
        )
        lines.extend(
            "| {source} | {line} | {item} | {rule} | {match_value} | "
            "{field} | {reason} |".format(
                **{key: _markdown_cell(value) for key, value in violation.items()}
            )
            for violation in completeness_summary["violations"]
        )
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate status policy, deadlines, and conditional completeness "
            "as one BESS readiness gate."
        )
    )
    parser.add_argument("paths", nargs="*", type=Path)
    parser.add_argument("--status-policy", type=Path, required=True)
    parser.add_argument("--completeness-policy", type=Path, required=True)
    parser.add_argument("--as-of", required=True, metavar="YYYY-MM-DD")
    parser.add_argument(
        "--deadline-fail-on",
        action="append",
        choices=DEADLINE_STATES,
        default=[],
        metavar="STATE",
        help=(
            "deadline state that fails the gate; repeat to replace the default "
            "overdue and missing states"
        ),
    )
    parser.add_argument(
        "--date-column",
        action="append",
        default=[],
        help="recognized deadline heading; repeat to replace the defaults",
    )
    parser.add_argument(
        "--terminal-status",
        action="append",
        default=[],
        help="status treated as closed; repeat to replace the defaults",
    )
    parser.add_argument(
        "--missing-date-value",
        action="append",
        default=[],
        help="value treated as an unset deadline; repeat to replace the defaults",
    )
    parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    parser.add_argument("--output", type=Path)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        as_of = parse_iso_date(args.as_of, "--as-of")
        paths = expand_paths(args.paths or [Path("templates")])
        status_policy = load_status_policy(args.status_policy)
        completeness_policy = load_completeness_policy(args.completeness_policy)
        report = evaluate_readiness(
            paths,
            status_policy=status_policy,
            status_policy_source=args.status_policy.as_posix(),
            completeness_policy=completeness_policy,
            completeness_policy_source=args.completeness_policy.as_posix(),
            as_of=as_of,
            deadline_fail_states=(
                args.deadline_fail_on or DEFAULT_DEADLINE_FAIL_STATES
            ),
            date_columns=args.date_column or DEFAULT_DATE_COLUMNS,
            terminal_statuses=args.terminal_status or DEFAULT_TERMINAL_STATUSES,
            missing_date_values=(
                args.missing_date_value or DEFAULT_MISSING_DATE_VALUES
            ),
        )
    except (OSError, ValueError) as error:
        print(f"Readiness gate failed: {error}", file=sys.stderr)
        return 1

    rendered = (
        json.dumps(report, indent=2) + "\n"
        if args.format == "json"
        else render_markdown(report)
    )
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    else:
        print(rendered, end="")

    if report["gate"]["result"] == "fail":
        details = ", ".join(
            f"{name} ({report['checks'][name]['finding_count']})"
            for name in report["gate"]["failed_checks"]
        )
        print(f"Readiness gate failed on: {details}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
