from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path
from typing import Sequence

try:
    from scripts.summarize_status import expand_paths, normalize_heading
    from scripts.validate_templates import table_blocks, table_cells
except ModuleNotFoundError:
    from summarize_status import expand_paths, normalize_heading
    from validate_templates import table_blocks, table_cells


GENERATED_MARKER = "<!-- generated by scripts/audit_document_control.py -->"
IDENTIFIER_PATTERN = re.compile(r"^[A-Z][A-Z0-9]*(?:-[A-Z0-9]+)*-\d+$")
REVISION_PATTERN = re.compile(r"^(?:rev(?:ision)?\s*)?([A-Z]|\d+)$", re.IGNORECASE)

ACCEPTED_STATUSES = ("Approved", "Accepted", "Released")
WORKING_STATUSES = ("Draft", "Under review", "Pending approval")
OBSOLETE_STATUSES = ("Superseded", "Withdrawn")
MISSING_VALUES = ("TBD", "TBC", "N/A", "NA", "-")

COLUMNS = {
    "document_id": ("Document ID", "Document Number"),
    "document_type": ("Document Type", "Document Title"),
    "system_area": ("System Area", "Area", "Subsystem"),
    "owner": ("Owner", "Document Owner"),
    "revision": ("Revision", "Revision Number"),
    "approval_status": ("Approval Status", "Document Status"),
    "issue_date": ("Issue Date", "Issued Date"),
    "supersedes_revision": ("Supersedes Revision", "Supersedes"),
    "evidence_link": ("Evidence Link", "Controlled Location"),
    "closeout_notes": ("Closeout Notes", "Notes"),
}


@dataclass(frozen=True)
class DocumentRevision:
    source: str
    line: int
    document_id: str
    document_type: str
    system_area: str
    owner: str
    revision: str
    approval_status: str
    issue_date: str
    supersedes_revision: str
    evidence_link: str
    closeout_notes: str


@dataclass(frozen=True)
class DocumentControlIssue:
    source: str
    line: int
    document_id: str
    revision: str
    kind: str
    detail: str


def _normalized_aliases(values: Sequence[str]) -> set[str]:
    return {normalize_heading(value) for value in values}


def _column_indices(header: Sequence[str], context: str) -> dict[str, int]:
    normalized_header = [normalize_heading(value) for value in header]
    indices: dict[str, int] = {}
    for field, aliases in COLUMNS.items():
        matches = [
            index
            for index, column in enumerate(normalized_header)
            if column in _normalized_aliases(aliases)
        ]
        if not matches:
            raise ValueError(
                f"{context}: missing required column for {field}: "
                + ", ".join(aliases)
            )
        if len(matches) > 1:
            columns = ", ".join(header[index] for index in matches)
            raise ValueError(f"{context}: ambiguous {field} columns: {columns}")
        indices[field] = matches[0]
    return indices


def _is_document_register_header(header: Sequence[str]) -> bool:
    normalized = {normalize_heading(value) for value in header}
    return bool(
        normalized & _normalized_aliases(COLUMNS["document_id"])
        and normalized & _normalized_aliases(COLUMNS["revision"])
        and normalized & _normalized_aliases(COLUMNS["approval_status"])
    )


def extract_document_revisions(path: Path) -> list[DocumentRevision]:
    """Extract rows from handover document-control registers."""

    lines = path.read_text(encoding="utf-8").splitlines()
    if lines and lines[0].strip() == GENERATED_MARKER:
        return []

    records: list[DocumentRevision] = []
    for start_line, block in table_blocks(lines):
        if len(block) < 3:
            continue
        header = table_cells(block[0])
        if not _is_document_register_header(header):
            continue
        indices = _column_indices(header, f"{path}:{start_line}")
        for offset, row in enumerate(block[2:], start=2):
            cells = table_cells(row)
            row_line = start_line + offset
            if len(cells) != len(header):
                raise ValueError(
                    f"{path}:{row_line}: table row has {len(cells)} cells; "
                    f"expected {len(header)}"
                )
            if not any(cells):
                continue
            values = {field: cells[index] for field, index in indices.items()}
            records.append(
                DocumentRevision(source=path.as_posix(), line=row_line, **values)
            )
    return records


def _is_missing(value: str, missing_values: Sequence[str] = MISSING_VALUES) -> bool:
    normalized_missing = {normalize_heading(item) for item in missing_values}
    return not value.strip() or normalize_heading(value) in normalized_missing


def _parse_date(value: str) -> date | None:
    try:
        parsed = date.fromisoformat(value)
    except ValueError:
        return None
    return parsed if parsed.isoformat() == value else None


def _parse_revision(value: str) -> tuple[str, int, str] | None:
    match = REVISION_PATTERN.fullmatch(value.strip())
    if not match:
        return None
    token = match.group(1).upper()
    if token.isdigit():
        ordinal = int(token)
        return "numeric", ordinal, f"Rev {ordinal}"
    return "alphabetic", ord(token) - ord("A"), f"Rev {token}"


def _normalized_statuses(values: Sequence[str], context: str) -> set[str]:
    normalized = [normalize_heading(value) for value in values]
    if not normalized or any(not value for value in normalized):
        raise ValueError(f"{context} must contain nonblank values")
    if len(set(normalized)) != len(normalized):
        raise ValueError(f"{context} contains duplicate values")
    return set(normalized)


def audit_document_control(
    records: Sequence[DocumentRevision],
    as_of: date,
    accepted_statuses: Sequence[str] = ACCEPTED_STATUSES,
    working_statuses: Sequence[str] = WORKING_STATUSES,
    obsolete_statuses: Sequence[str] = OBSOLETE_STATUSES,
    missing_values: Sequence[str] = MISSING_VALUES,
) -> list[DocumentControlIssue]:
    """Return deterministic revision-history and release-control findings."""

    accepted = _normalized_statuses(accepted_statuses, "accepted statuses")
    working = _normalized_statuses(working_statuses, "working statuses")
    obsolete = _normalized_statuses(obsolete_statuses, "obsolete statuses")
    if accepted & working or accepted & obsolete or working & obsolete:
        raise ValueError("document status classifications must not overlap")
    known_statuses = accepted | working | obsolete
    accepted_display = ", ".join(accepted_statuses)
    obsolete_display = ", ".join(obsolete_statuses)

    issues: list[DocumentControlIssue] = []
    groups: dict[str, list[DocumentRevision]] = {}
    parsed_revisions: dict[DocumentRevision, tuple[str, int, str]] = {}
    parsed_dates: dict[DocumentRevision, date] = {}
    seen_keys: dict[tuple[str, str], DocumentRevision] = {}

    def add(record: DocumentRevision, kind: str, detail: str) -> None:
        issues.append(
            DocumentControlIssue(
                source=record.source,
                line=record.line,
                document_id=record.document_id or f"Row {record.line}",
                revision=record.revision or "-",
                kind=kind,
                detail=detail,
            )
        )

    for record in records:
        required = {
            "Document ID": record.document_id,
            "Document Type": record.document_type,
            "System Area": record.system_area,
            "Owner": record.owner,
            "Revision": record.revision,
            "Approval Status": record.approval_status,
            "Issue Date": record.issue_date,
        }
        missing = [
            name
            for name, value in required.items()
            if _is_missing(value, missing_values)
        ]
        if missing:
            add(
                record,
                "missing_required_field",
                "missing controlled value for " + ", ".join(missing),
            )

        if record.document_id and not IDENTIFIER_PATTERN.fullmatch(record.document_id):
            add(
                record,
                "invalid_document_id",
                "Document ID must use an uppercase project prefix and numeric suffix",
            )

        parsed_revision = _parse_revision(record.revision)
        if not _is_missing(record.revision, missing_values):
            if parsed_revision is None:
                add(
                    record,
                    "invalid_revision",
                    "Revision must use Rev A or Rev 2 syntax",
                )
            else:
                parsed_revisions[record] = parsed_revision

        parsed_date = _parse_date(record.issue_date)
        if not _is_missing(record.issue_date, missing_values):
            if parsed_date is None:
                add(
                    record,
                    "invalid_issue_date",
                    "Issue Date must use YYYY-MM-DD",
                )
            else:
                parsed_dates[record] = parsed_date
                if parsed_date > as_of:
                    add(
                        record,
                        "future_issue_date",
                        f"Issue Date is after the audit date {as_of.isoformat()}",
                    )

        normalized_status = normalize_heading(record.approval_status)
        if (
            not _is_missing(record.approval_status, missing_values)
            and normalized_status not in known_statuses
        ):
            add(
                record,
                "invalid_approval_status",
                "Approval Status is outside the controlled vocabulary",
            )

        if normalized_status in accepted | obsolete and _is_missing(
            record.evidence_link, missing_values
        ):
            add(
                record,
                "missing_controlled_location",
                f"{record.approval_status} revisions require an Evidence Link",
            )

        if record.document_id:
            groups.setdefault(record.document_id.casefold(), []).append(record)
        if record.document_id and parsed_revision is not None:
            key = (record.document_id.casefold(), parsed_revision[2].casefold())
            if key in seen_keys:
                first = seen_keys[key]
                add(
                    record,
                    "duplicate_document_revision",
                    f"duplicates {first.source}:{first.line}",
                )
            else:
                seen_keys[key] = record

    for group in groups.values():
        first = group[0]
        baseline_type = normalize_heading(first.document_type)
        baseline_area = normalize_heading(first.system_area)
        for record in group[1:]:
            if (
                baseline_type
                and normalize_heading(record.document_type) != baseline_type
            ):
                add(
                    record,
                    "inconsistent_document_type",
                    f"does not match {first.source}:{first.line}",
                )
            if baseline_area and normalize_heading(record.system_area) != baseline_area:
                add(
                    record,
                    "inconsistent_system_area",
                    f"does not match {first.source}:{first.line}",
                )

        valid = [record for record in group if record in parsed_revisions]
        if not valid:
            continue
        baseline_scheme = parsed_revisions[valid[0]][0]
        chain: list[DocumentRevision] = []
        seen_ordinals: set[int] = set()
        for record in valid:
            scheme, ordinal, _ = parsed_revisions[record]
            if scheme != baseline_scheme:
                add(
                    record,
                    "inconsistent_revision_scheme",
                    f"document history uses both {baseline_scheme} and {scheme} revisions",
                )
                continue
            if ordinal not in seen_ordinals:
                chain.append(record)
                seen_ordinals.add(ordinal)
        chain.sort(key=lambda item: parsed_revisions[item][1])
        if not chain:
            continue

        for index, record in enumerate(chain):
            status = normalize_heading(record.approval_status)
            if index < len(chain) - 1 and status not in obsolete:
                add(
                    record,
                    "historical_revision_not_obsolete",
                    f"a non-latest revision must use one of: {obsolete_display}",
                )
            if index == len(chain) - 1 and status not in accepted:
                add(
                    record,
                    "latest_revision_not_approved",
                    f"the latest revision must use one of: {accepted_display}",
                )

            if index == 0:
                if not _is_missing(record.supersedes_revision, missing_values):
                    add(
                        record,
                        "unexpected_supersedes_revision",
                        "the earliest recorded revision must not supersede another",
                    )
                continue

            previous = chain[index - 1]
            previous_revision = parsed_revisions[previous]
            supersedes = _parse_revision(record.supersedes_revision)
            if _is_missing(record.supersedes_revision, missing_values):
                add(
                    record,
                    "missing_supersedes_revision",
                    f"must supersede {previous_revision[2]}",
                )
            elif supersedes is None or supersedes[:2] != previous_revision[:2]:
                add(
                    record,
                    "incorrect_supersedes_revision",
                    f"must supersede the previous recorded revision {previous_revision[2]}",
                )

            current_date = parsed_dates.get(record)
            previous_date = parsed_dates.get(previous)
            if current_date and previous_date and current_date <= previous_date:
                add(
                    record,
                    "non_increasing_issue_date",
                    f"must be later than {previous_revision[2]} issued {previous.issue_date}",
                )

    return issues


def _status_category(
    status: str,
    accepted: set[str],
    working: set[str],
    obsolete: set[str],
) -> str:
    normalized = normalize_heading(status)
    if normalized in accepted:
        return "accepted"
    if normalized in working:
        return "working"
    if normalized in obsolete:
        return "obsolete"
    return "unknown"


def summarize_document_control(
    records: Sequence[DocumentRevision],
    issues: Sequence[DocumentControlIssue],
    as_of: date,
    accepted_statuses: Sequence[str] = ACCEPTED_STATUSES,
    working_statuses: Sequence[str] = WORKING_STATUSES,
    obsolete_statuses: Sequence[str] = OBSOLETE_STATUSES,
) -> dict[str, object]:
    accepted = _normalized_statuses(accepted_statuses, "accepted statuses")
    working = _normalized_statuses(working_statuses, "working statuses")
    obsolete = _normalized_statuses(obsolete_statuses, "obsolete statuses")
    categories = Counter(
        _status_category(record.approval_status, accepted, working, obsolete)
        for record in records
    )
    revisions: list[dict[str, object]] = []
    for record in records:
        item = asdict(record)
        item["status_category"] = _status_category(
            record.approval_status, accepted, working, obsolete
        )
        revisions.append(item)
    return {
        "as_of": as_of.isoformat(),
        "source_files": sorted({record.source for record in records}),
        "document_count": len(
            {
                record.document_id.casefold()
                for record in records
                if record.document_id.strip()
            }
        ),
        "revision_count": len(records),
        "status_category_counts": {
            category: categories[category]
            for category in ("accepted", "working", "obsolete", "unknown")
        },
        "issue_count": len(issues),
        "issues": [asdict(issue) for issue in issues],
        "revisions": revisions,
    }


def _markdown_cell(value: object) -> str:
    if value is None or value == "":
        return "-"
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_markdown(summary: dict[str, object]) -> str:
    lines = [
        GENERATED_MARKER,
        "<!-- markdownlint-disable MD013 -->",
        "",
        "# Handover Document-Control Audit",
        "",
        f"As of: {summary['as_of']}  ",
        f"Source files: {len(summary['source_files'])}  ",
        f"Documents: {summary['document_count']}  ",
        f"Revisions: {summary['revision_count']}  ",
        f"Issues: {summary['issue_count']}",
        "",
        "## Status Categories",
        "",
        "| Category | Count |",
        "| --- | ---: |",
    ]
    for category, count in summary["status_category_counts"].items():
        lines.append(f"| {category} | {count} |")
    if summary["issues"]:
        lines.extend(
            [
                "",
                "## Issues",
                "",
                "| Source | Line | Document | Revision | Kind | Detail |",
                "| --- | ---: | --- | --- | --- | --- |",
            ]
        )
        for issue in summary["issues"]:
            lines.append(
                "| {source} | {line} | {document_id} | {revision} | "
                "{kind} | {detail} |".format(
                    **{key: _markdown_cell(value) for key, value in issue.items()}
                )
            )
    lines.extend(
        [
            "",
            "## Revision Register",
            "",
            "| Document | Revision | Issue Date | Supersedes | Status | Category | "
            "Owner | Evidence |",
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for revision in summary["revisions"]:
        lines.append(
            "| {document_id} | {revision} | {issue_date} | "
            "{supersedes_revision} | {approval_status} | {status_category} | "
            "{owner} | {evidence_link} |".format(
                **{key: _markdown_cell(value) for key, value in revision.items()}
            )
        )
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Audit BESS handover document revision and release control."
    )
    parser.add_argument("paths", nargs="*", type=Path)
    parser.add_argument("--as-of", required=True, metavar="YYYY-MM-DD")
    parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--accepted-status", action="append")
    parser.add_argument("--working-status", action="append")
    parser.add_argument("--obsolete-status", action="append")
    parser.add_argument("--missing-value", action="append")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        as_of = _parse_date(args.as_of)
        if as_of is None:
            raise ValueError("--as-of must use YYYY-MM-DD")
        accepted = args.accepted_status or ACCEPTED_STATUSES
        working = args.working_status or WORKING_STATUSES
        obsolete = args.obsolete_status or OBSOLETE_STATUSES
        missing = args.missing_value or MISSING_VALUES
        inputs = args.paths or [Path("examples/document-control-passing.md")]
        paths = expand_paths(inputs)
        records = [
            record
            for path in paths
            for record in extract_document_revisions(path)
        ]
        if not records:
            raise ValueError("no handover document-control rows found")
        issues = audit_document_control(
            records,
            as_of,
            accepted_statuses=accepted,
            working_statuses=working,
            obsolete_statuses=obsolete,
            missing_values=missing,
        )
    except (OSError, ValueError) as error:
        print(f"Document-control audit failed: {error}", file=sys.stderr)
        return 1

    summary = summarize_document_control(
        records,
        issues,
        as_of,
        accepted_statuses=accepted,
        working_statuses=working,
        obsolete_statuses=obsolete,
    )
    rendered = (
        json.dumps(summary, indent=2) + "\n"
        if args.format == "json"
        else render_markdown(summary)
    )
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    else:
        print(rendered, end="")

    for issue in issues:
        print(
            f"{issue.source}:{issue.line}: {issue.document_id} "
            f"{issue.revision}: {issue.kind}: {issue.detail}",
            file=sys.stderr,
        )
    if issues:
        print(
            f"Document-control gate failed with {len(issues)} issue(s).",
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
