from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import date
from pathlib import Path
from typing import Sequence

try:
    from scripts.summarize_status import (
        BLANK_STATUS,
        expand_paths,
        is_status_legend,
        normalize_heading,
        status_column_index,
    )
    from scripts.validate_templates import table_blocks, table_cells
except ModuleNotFoundError:
    from summarize_status import (
        BLANK_STATUS,
        expand_paths,
        is_status_legend,
        normalize_heading,
        status_column_index,
    )
    from validate_templates import table_blocks, table_cells


GENERATED_MARKER = "<!-- generated by scripts/audit_deadlines.py -->"
DEFAULT_DATE_COLUMNS = ("Due Date", "Target Close Date", "Required By")
DEFAULT_MISSING_DATE_VALUES = ("TBD", "TBC", "N/A", "NA", "-")
DEFAULT_TERMINAL_STATUSES = (
    "Accepted",
    "Approved",
    "Closed",
    "Complete",
    "Completed",
)
DEADLINE_STATES = ("overdue", "due_today", "upcoming", "missing", "closed")


@dataclass(frozen=True)
class DeadlineRecord:
    source: str
    line: int
    item: str
    status: str
    status_column: str
    deadline: str
    deadline_column: str
    state: str
    days_to_deadline: int | None


def parse_iso_date(value: str, context: str) -> date:
    try:
        parsed = date.fromisoformat(value)
    except ValueError as error:
        raise ValueError(f"{context} must use YYYY-MM-DD") from error
    if parsed.isoformat() != value:
        raise ValueError(f"{context} must use YYYY-MM-DD")
    return parsed


def normalized_values(values: Sequence[str], context: str) -> tuple[str, ...]:
    cleaned = tuple(value.strip() for value in values)
    if any(not value for value in cleaned):
        raise ValueError(f"{context} must contain nonempty values")
    normalized = tuple(normalize_heading(value) for value in cleaned)
    if len(normalized) != len(set(normalized)):
        raise ValueError(f"{context} contains case-insensitive duplicates")
    return normalized


def extract_deadline_records(
    path: Path,
    as_of: date,
    date_columns: Sequence[str] = DEFAULT_DATE_COLUMNS,
    terminal_statuses: Sequence[str] = DEFAULT_TERMINAL_STATUSES,
    missing_date_values: Sequence[str] = DEFAULT_MISSING_DATE_VALUES,
) -> list[DeadlineRecord]:
    """Extract deadline states from status-bearing Markdown table rows."""

    normalized_date_columns = set(normalized_values(date_columns, "date columns"))
    normalized_terminal_statuses = set(
        normalized_values(terminal_statuses, "terminal statuses")
    )
    normalized_missing_date_values = set(
        normalized_values(missing_date_values, "missing date values")
    )
    lines = path.read_text(encoding="utf-8").splitlines()
    if lines and lines[0].strip().startswith("<!-- generated by scripts/"):
        return []

    records: list[DeadlineRecord] = []
    for start_line, block in table_blocks(lines):
        if len(block) < 3:
            continue
        header = table_cells(block[0])
        if is_status_legend(header):
            continue
        status_index = status_column_index(header)
        if status_index is None:
            continue
        deadline_indexes = [
            index
            for index, cell in enumerate(header)
            if normalize_heading(cell) in normalized_date_columns
        ]
        if len(deadline_indexes) > 1:
            columns = ", ".join(header[index] for index in deadline_indexes)
            raise ValueError(
                f"{path}:{start_line}: table has multiple deadline columns: {columns}"
            )
        if not deadline_indexes:
            continue
        deadline_index = deadline_indexes[0]

        for offset, row in enumerate(block[2:], start=2):
            cells = table_cells(row)
            row_line = start_line + offset
            if len(cells) != len(header):
                raise ValueError(
                    f"{path}:{row_line}: table row has {len(cells)} cells; "
                    f"expected {len(header)}"
                )
            if not any(cells):
                continue

            item = next(
                (
                    cell
                    for index, cell in enumerate(cells)
                    if index not in {status_index, deadline_index} and cell
                ),
                f"Row {row_line}",
            )
            status = cells[status_index] or BLANK_STATUS
            raw_deadline = cells[deadline_index]
            deadline = None
            days_to_deadline = None
            if (
                raw_deadline
                and normalize_heading(raw_deadline)
                not in normalized_missing_date_values
            ):
                deadline = parse_iso_date(
                    raw_deadline,
                    f"{path}:{row_line}: {header[deadline_index]}",
                )
                days_to_deadline = (deadline - as_of).days

            if normalize_heading(status) in normalized_terminal_statuses:
                state = "closed"
            elif deadline is None:
                state = "missing"
            elif days_to_deadline is not None and days_to_deadline < 0:
                state = "overdue"
            elif days_to_deadline == 0:
                state = "due_today"
            else:
                state = "upcoming"

            records.append(
                DeadlineRecord(
                    source=path.as_posix(),
                    line=row_line,
                    item=item,
                    status=status,
                    status_column=header[status_index],
                    deadline=raw_deadline,
                    deadline_column=header[deadline_index],
                    state=state,
                    days_to_deadline=days_to_deadline,
                )
            )
    return records


def summarize_deadlines(
    records: Sequence[DeadlineRecord], as_of: date
) -> dict[str, object]:
    counts = Counter(record.state for record in records)
    return {
        "as_of": as_of.isoformat(),
        "source_files": sorted({record.source for record in records}),
        "row_count": len(records),
        "state_counts": {state: counts[state] for state in DEADLINE_STATES},
        "items": [asdict(record) for record in records],
    }


def _markdown_cell(value: object) -> str:
    if value is None or value == "":
        return "-"
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_markdown(summary: dict[str, object]) -> str:
    lines = [
        GENERATED_MARKER,
        "<!-- markdownlint-disable MD013 -->",
        "",
        "# Readiness Deadline Audit",
        "",
        f"As of: {summary['as_of']}  ",
        f"Source files: {len(summary['source_files'])}  ",
        f"Deadline rows: {summary['row_count']}",
        "",
        "## Counts",
        "",
        "| State | Count |",
        "| --- | ---: |",
    ]
    state_counts = summary["state_counts"]
    lines.extend(f"| {state} | {state_counts[state]} |" for state in DEADLINE_STATES)
    lines.extend(
        [
            "",
            "## Items",
            "",
            "| Source | Line | Item | Status Column | Status | Deadline Column | "
            "Deadline | State | Days |",
            "| --- | ---: | --- | --- | --- | --- | --- | --- | ---: |",
        ]
    )
    for item in summary["items"]:
        lines.append(
            "| {source} | {line} | {item} | {status_column} | {status} | "
            "{deadline_column} | {deadline} | {state} | {days} |".format(
                source=_markdown_cell(item["source"]),
                line=item["line"],
                item=_markdown_cell(item["item"]),
                status_column=_markdown_cell(item["status_column"]),
                status=_markdown_cell(item["status"]),
                deadline_column=_markdown_cell(item["deadline_column"]),
                deadline=_markdown_cell(item["deadline"]),
                state=item["state"],
                days=_markdown_cell(item["days_to_deadline"]),
            )
        )
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Audit dated BESS readiness actions from Markdown tables."
    )
    parser.add_argument("paths", nargs="*", type=Path)
    parser.add_argument("--as-of", required=True, metavar="YYYY-MM-DD")
    parser.add_argument(
        "--date-column",
        action="append",
        default=[],
        help="recognized deadline heading; repeat to replace the defaults",
    )
    parser.add_argument(
        "--terminal-status",
        action="append",
        default=[],
        help="status treated as closed; repeat to replace the defaults",
    )
    parser.add_argument(
        "--missing-date-value",
        action="append",
        default=[],
        help="value treated as an unset deadline; repeat to replace the defaults",
    )
    parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    parser.add_argument("--output", type=Path)
    parser.add_argument(
        "--fail-on",
        action="append",
        choices=DEADLINE_STATES,
        default=[],
        metavar="STATE",
        help="exit 2 when this state occurs; repeat for multiple states",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        as_of = parse_iso_date(args.as_of, "--as-of")
        date_columns = args.date_column or DEFAULT_DATE_COLUMNS
        terminal_statuses = args.terminal_status or DEFAULT_TERMINAL_STATUSES
        missing_date_values = args.missing_date_value or DEFAULT_MISSING_DATE_VALUES
        normalized_values(date_columns, "date columns")
        normalized_values(terminal_statuses, "terminal statuses")
        normalized_values(missing_date_values, "missing date values")
        inputs = args.paths or [Path("templates")]
        paths = expand_paths(inputs)
        records = [
            record
            for path in paths
            for record in extract_deadline_records(
                path,
                as_of,
                date_columns,
                terminal_statuses,
                missing_date_values,
            )
        ]
    except (OSError, ValueError) as error:
        print(f"Deadline audit failed: {error}", file=sys.stderr)
        return 1

    if not records:
        print("Deadline audit failed: no deadline-bearing rows found.", file=sys.stderr)
        return 1

    summary = summarize_deadlines(records, as_of)
    rendered = (
        json.dumps(summary, indent=2) + "\n"
        if args.format == "json"
        else render_markdown(summary)
    )
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    else:
        print(rendered, end="")

    failed_states = set(args.fail_on)
    matched = {
        state: summary["state_counts"][state]
        for state in DEADLINE_STATES
        if state in failed_states and summary["state_counts"][state]
    }
    if matched:
        details = ", ".join(f"{state} ({count})" for state, count in matched.items())
        print(f"Deadline audit gate failed on: {details}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
