from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Sequence

try:
    from scripts.validate_templates import table_blocks, table_cells
except ModuleNotFoundError:
    from validate_templates import table_blocks, table_cells


BLANK_STATUS = "(blank)"
GENERATED_MARKER = "<!-- generated by scripts/summarize_status.py -->"


@dataclass(frozen=True)
class StatusRecord:
    source: str
    line: int
    item: str
    status: str
    column: str


def normalize_heading(value: str) -> str:
    return " ".join(value.casefold().split())


def status_column_index(header: list[str]) -> int | None:
    matches = [
        index
        for index, cell in enumerate(header)
        if normalize_heading(cell) == "status"
        or normalize_heading(cell).endswith(" status")
    ]
    if len(matches) > 1:
        raise ValueError("table has more than one status column")
    return matches[0] if matches else None


def is_status_legend(header: list[str]) -> bool:
    normalized = [normalize_heading(cell) for cell in header]
    return (
        len(normalized) == 2
        and normalized[0] == "status"
        and normalized[1]
        in {
            "definition",
            "meaning",
        }
    )


def extract_status_records(path: Path) -> list[StatusRecord]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if lines and lines[0].strip() == GENERATED_MARKER:
        return []
    records: list[StatusRecord] = []
    for start_line, block in table_blocks(lines):
        if len(block) < 3:
            continue
        header = table_cells(block[0])
        if is_status_legend(header):
            continue
        status_index = status_column_index(header)
        if status_index is None:
            continue

        for offset, row in enumerate(block[2:], start=2):
            cells = table_cells(row)
            row_line = start_line + offset
            if len(cells) != len(header):
                raise ValueError(
                    f"{path}:{row_line}: table row has {len(cells)} cells; "
                    f"expected {len(header)}"
                )
            item = next(
                (
                    cell
                    for index, cell in enumerate(cells)
                    if index != status_index and cell
                ),
                f"Row {row_line}",
            )
            records.append(
                StatusRecord(
                    source=path.as_posix(),
                    line=row_line,
                    item=item,
                    status=cells[status_index] or BLANK_STATUS,
                    column=header[status_index],
                )
            )
    return records


def expand_paths(inputs: Sequence[Path]) -> list[Path]:
    paths: list[Path] = []
    for input_path in inputs:
        if input_path.is_dir():
            paths.extend(sorted(input_path.glob("*.md")))
        elif input_path.is_file():
            paths.append(input_path)
        else:
            raise FileNotFoundError(f"input does not exist: {input_path}")

    unique: list[Path] = []
    seen: set[Path] = set()
    for path in paths:
        resolved = path.resolve()
        if resolved not in seen:
            seen.add(resolved)
            unique.append(path)
    return unique


def summarize_records(records: Sequence[StatusRecord]) -> dict[str, object]:
    counts = Counter(record.status for record in records)
    ordered_counts = {
        status: counts[status]
        for status in sorted(counts, key=lambda value: value.casefold())
    }
    return {
        "source_files": sorted({record.source for record in records}),
        "row_count": len(records),
        "status_counts": ordered_counts,
        "items": [asdict(record) for record in records],
    }


def _markdown_cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_markdown(summary: dict[str, object]) -> str:
    source_files = summary["source_files"]
    status_counts = summary["status_counts"]
    items = summary["items"]
    lines = [
        GENERATED_MARKER,
        "<!-- markdownlint-disable MD013 -->",
        "",
        "# Readiness Status Summary",
        "",
        f"Source files: {len(source_files)}  ",
        f"Status rows: {summary['row_count']}",
        "",
        "## Counts",
        "",
        "| Status | Count |",
        "| --- | ---: |",
    ]
    lines.extend(
        f"| {_markdown_cell(status)} | {count} |"
        for status, count in status_counts.items()
    )
    lines.extend(
        [
            "",
            "## Items",
            "",
            "| Source | Line | Item | Status |",
            "| --- | ---: | --- | --- |",
        ]
    )
    lines.extend(
        "| {source} | {line} | {item} | {status} |".format(
            source=_markdown_cell(item["source"]),
            line=item["line"],
            item=_markdown_cell(item["item"]),
            status=_markdown_cell(item["status"]),
        )
        for item in items
    )
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Summarize status columns from filled BESS Markdown tables."
    )
    parser.add_argument("paths", nargs="*", type=Path)
    parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    parser.add_argument("--output", type=Path)
    parser.add_argument(
        "--fail-on",
        action="append",
        default=[],
        metavar="STATUS",
        help="exit 2 when this status occurs; repeat for multiple states",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        inputs = args.paths or [Path("templates")]
        paths = expand_paths(inputs)
        records = [record for path in paths for record in extract_status_records(path)]
    except (OSError, ValueError) as error:
        print(f"Status summary failed: {error}", file=sys.stderr)
        return 1

    if not records:
        print("Status summary failed: no status-bearing rows found.", file=sys.stderr)
        return 1

    summary = summarize_records(records)
    if args.format == "json":
        rendered = json.dumps(summary, indent=2) + "\n"
    else:
        rendered = render_markdown(summary)

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    else:
        print(rendered, end="")

    blocked = {status.casefold() for status in args.fail_on}
    matched = sorted(
        {record.status for record in records if record.status.casefold() in blocked},
        key=str.casefold,
    )
    if matched:
        print(
            "Status summary gate failed on: " + ", ".join(matched),
            file=sys.stderr,
        )
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
