from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Sequence

try:
    from scripts.validate_templates import table_blocks, table_cells
except ModuleNotFoundError:
    from validate_templates import table_blocks, table_cells


BLANK_STATUS = "(blank)"
GENERATED_MARKER = "<!-- generated by scripts/summarize_status.py -->"


@dataclass(frozen=True)
class StatusRecord:
    source: str
    line: int
    item: str
    status: str
    column: str


@dataclass(frozen=True)
class StatusPolicy:
    allowed_statuses: tuple[str, ...]
    blocking_statuses: tuple[str, ...]
    require_status: bool


@dataclass(frozen=True)
class PolicyViolation:
    source: str
    line: int
    item: str
    status: str
    reason: str


def normalize_heading(value: str) -> str:
    return " ".join(value.casefold().split())


def status_column_index(header: list[str]) -> int | None:
    matches = [
        index
        for index, cell in enumerate(header)
        if normalize_heading(cell) == "status"
        or normalize_heading(cell).endswith(" status")
    ]
    if len(matches) > 1:
        raise ValueError("table has more than one status column")
    return matches[0] if matches else None


def is_status_legend(header: list[str]) -> bool:
    normalized = [normalize_heading(cell) for cell in header]
    return (
        len(normalized) == 2
        and normalized[0] == "status"
        and normalized[1]
        in {
            "definition",
            "meaning",
        }
    )


def extract_status_records(path: Path) -> list[StatusRecord]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if lines and lines[0].strip() == GENERATED_MARKER:
        return []
    records: list[StatusRecord] = []
    for start_line, block in table_blocks(lines):
        if len(block) < 3:
            continue
        header = table_cells(block[0])
        if is_status_legend(header):
            continue
        status_index = status_column_index(header)
        if status_index is None:
            continue

        for offset, row in enumerate(block[2:], start=2):
            cells = table_cells(row)
            row_line = start_line + offset
            if len(cells) != len(header):
                raise ValueError(
                    f"{path}:{row_line}: table row has {len(cells)} cells; "
                    f"expected {len(header)}"
                )
            item = next(
                (
                    cell
                    for index, cell in enumerate(cells)
                    if index != status_index and cell
                ),
                f"Row {row_line}",
            )
            records.append(
                StatusRecord(
                    source=path.as_posix(),
                    line=row_line,
                    item=item,
                    status=cells[status_index] or BLANK_STATUS,
                    column=header[status_index],
                )
            )
    return records


def expand_paths(inputs: Sequence[Path]) -> list[Path]:
    paths: list[Path] = []
    for input_path in inputs:
        if input_path.is_dir():
            paths.extend(sorted(input_path.glob("*.md")))
        elif input_path.is_file():
            paths.append(input_path)
        else:
            raise FileNotFoundError(f"input does not exist: {input_path}")

    unique: list[Path] = []
    seen: set[Path] = set()
    for path in paths:
        resolved = path.resolve()
        if resolved not in seen:
            seen.add(resolved)
            unique.append(path)
    return unique


def _policy_statuses(document: dict[str, object], key: str) -> tuple[str, ...]:
    raw_statuses = document.get(key, [])
    if not isinstance(raw_statuses, list) or any(
        not isinstance(status, str) or not status.strip() for status in raw_statuses
    ):
        raise ValueError(f"policy {key} must be a list of nonempty strings")
    statuses = tuple(status.strip() for status in raw_statuses)
    normalized = [status.casefold() for status in statuses]
    if len(normalized) != len(set(normalized)):
        raise ValueError(f"policy {key} contains case-insensitive duplicates")
    return statuses


def load_status_policy(path: Path) -> StatusPolicy:
    """Load and validate a project-specific readiness status policy."""

    document = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        raise ValueError("status policy root must be a JSON object")
    allowed_keys = {"allowed_statuses", "blocking_statuses", "require_status"}
    unknown_keys = sorted(set(document) - allowed_keys)
    if unknown_keys:
        raise ValueError("status policy has unknown fields: " + ", ".join(unknown_keys))

    require_status = document.get("require_status", False)
    if not isinstance(require_status, bool):
        raise ValueError("policy require_status must be true or false")
    allowed_statuses = _policy_statuses(document, "allowed_statuses")
    blocking_statuses = _policy_statuses(document, "blocking_statuses")
    if allowed_statuses:
        allowed = {status.casefold() for status in allowed_statuses}
        outside_allowlist = [
            status for status in blocking_statuses if status.casefold() not in allowed
        ]
        if outside_allowlist:
            raise ValueError(
                "policy blocking_statuses must also be allowed: "
                + ", ".join(outside_allowlist)
            )
    return StatusPolicy(
        allowed_statuses=allowed_statuses,
        blocking_statuses=blocking_statuses,
        require_status=require_status,
    )


def evaluate_status_policy(
    records: Sequence[StatusRecord], policy: StatusPolicy
) -> list[PolicyViolation]:
    """Return line-level blank, unknown, and blocking status violations."""

    allowed = {status.casefold() for status in policy.allowed_statuses}
    blocking = {status.casefold() for status in policy.blocking_statuses}
    violations: list[PolicyViolation] = []
    for record in records:
        normalized = record.status.casefold()
        reason = None
        if record.status == BLANK_STATUS:
            if policy.require_status:
                reason = "status is required"
        elif allowed and normalized not in allowed:
            reason = "status is not in allowed_statuses"
        elif normalized in blocking:
            reason = "status is blocking"
        if reason:
            violations.append(
                PolicyViolation(
                    source=record.source,
                    line=record.line,
                    item=record.item,
                    status=record.status,
                    reason=reason,
                )
            )
    return violations


def summarize_records(records: Sequence[StatusRecord]) -> dict[str, object]:
    counts = Counter(record.status for record in records)
    ordered_counts = {
        status: counts[status]
        for status in sorted(counts, key=lambda value: value.casefold())
    }
    return {
        "source_files": sorted({record.source for record in records}),
        "row_count": len(records),
        "status_counts": ordered_counts,
        "items": [asdict(record) for record in records],
    }


def _markdown_cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_markdown(summary: dict[str, object]) -> str:
    source_files = summary["source_files"]
    status_counts = summary["status_counts"]
    items = summary["items"]
    lines = [
        GENERATED_MARKER,
        "<!-- markdownlint-disable MD013 -->",
        "",
        "# Readiness Status Summary",
        "",
        f"Source files: {len(source_files)}  ",
        f"Status rows: {summary['row_count']}",
        "",
        "## Counts",
        "",
        "| Status | Count |",
        "| --- | ---: |",
    ]
    lines.extend(
        f"| {_markdown_cell(status)} | {count} |"
        for status, count in status_counts.items()
    )
    if "status_policy" in summary:
        policy = summary["status_policy"]
        violations = summary["policy_violations"]
        lines.extend(
            [
                "",
                "## Policy Evaluation",
                "",
                f"Policy source: {_markdown_cell(policy['source'])}  ",
                f"Violations: {len(violations)}",
            ]
        )
        if violations:
            lines.extend(
                [
                    "",
                    "| Source | Line | Item | Status | Reason |",
                    "| --- | ---: | --- | --- | --- |",
                ]
            )
            lines.extend(
                "| {source} | {line} | {item} | {status} | {reason} |".format(
                    **{key: _markdown_cell(value) for key, value in violation.items()}
                )
                for violation in violations
            )
    lines.extend(
        [
            "",
            "## Items",
            "",
            "| Source | Line | Item | Status |",
            "| --- | ---: | --- | --- |",
        ]
    )
    lines.extend(
        "| {source} | {line} | {item} | {status} |".format(
            source=_markdown_cell(item["source"]),
            line=item["line"],
            item=_markdown_cell(item["item"]),
            status=_markdown_cell(item["status"]),
        )
        for item in items
    )
    return "\n".join(lines) + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Summarize status columns from filled BESS Markdown tables."
    )
    parser.add_argument("paths", nargs="*", type=Path)
    parser.add_argument("--format", choices=("markdown", "json"), default="markdown")
    parser.add_argument("--output", type=Path)
    parser.add_argument(
        "--policy",
        type=Path,
        help="JSON status policy with allowed, blocking, and completeness rules",
    )
    parser.add_argument(
        "--fail-on",
        action="append",
        default=[],
        metavar="STATUS",
        help="exit 2 when this status occurs; repeat for multiple states",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        inputs = args.paths or [Path("templates")]
        paths = expand_paths(inputs)
        records = [record for path in paths for record in extract_status_records(path)]
        policy = load_status_policy(args.policy) if args.policy else None
    except (OSError, ValueError) as error:
        print(f"Status summary failed: {error}", file=sys.stderr)
        return 1

    if not records:
        print("Status summary failed: no status-bearing rows found.", file=sys.stderr)
        return 1

    summary = summarize_records(records)
    policy_violations: list[PolicyViolation] = []
    if policy:
        policy_violations = evaluate_status_policy(records, policy)
        summary["status_policy"] = {
            "source": args.policy.as_posix(),
            **asdict(policy),
        }
        summary["policy_violations"] = [
            asdict(violation) for violation in policy_violations
        ]
    if args.format == "json":
        rendered = json.dumps(summary, indent=2) + "\n"
    else:
        rendered = render_markdown(summary)

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    else:
        print(rendered, end="")

    blocked = {status.casefold() for status in args.fail_on}
    matched = sorted(
        {record.status for record in records if record.status.casefold() in blocked},
        key=str.casefold,
    )
    if matched:
        print(
            "Status summary gate failed on: " + ", ".join(matched),
            file=sys.stderr,
        )
    for violation in policy_violations:
        print(
            f"{violation.source}:{violation.line}: {violation.item}: "
            f"{violation.reason} ({violation.status})",
            file=sys.stderr,
        )
    if policy_violations:
        print(
            f"Status policy gate failed with {len(policy_violations)} violation(s).",
            file=sys.stderr,
        )
    if matched or policy_violations:
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
